import { useEffect,useState } from 'react';
import { useTranslation } from "react-i18next";
import { useParams } from 'react-router-dom';
import { supabase } from '../../services/supabase';
import { adminGetExams,adminCreateExam,adminUpdateExam,adminDeleteExam,adminAddQuestion,adminDeleteQuestion,adminGetAttempts } from '../../services/examService';

const emptyExam={title:'الاختبار النهائي',description:'',passing_score:70,max_attempts:3,is_final:true,is_published:false};
export default function AdminExams(){
 const { i18n } = useTranslation();const {courseId}=useParams();const [course,setCourse]=useState(null),[exams,setExams]=useState([]),[attempts,setAttempts]=useState([]),[form,setForm]=useState(emptyExam),[selected,setSelected]=useState(null),[q,setQ]=useState({question_text:'',options:['','','',''],correct_answer:'',points:1,order_number:1}),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){try{setError('');const [{data:c,error:ce},e,a]=await Promise.all([supabase.from('courses').select('id,title').eq('id',courseId).single(),adminGetExams(courseId),adminGetAttempts(courseId)]);if(ce)throw ce;setCourse(c);setExams(e);setAttempts(a);if(selected){const fresh=e.find(x=>x.id===selected.id);setSelected(fresh||null)}}catch(e){setError(e.message||'تعذر تحميل الاختبارات')}}useEffect(()=>{load()},[courseId]);
 async function create(e){e.preventDefault();try{const item=await adminCreateExam({...form,course_id:courseId,passing_score:Number(form.passing_score),max_attempts:Number(form.max_attempts)});setForm(emptyExam);setSelected(item);setMessage('تم إنشاء الاختبار');await load()}catch(e){setError(e.message)}}
 async function toggle(exam,key){try{await adminUpdateExam(exam.id,{[key]:!exam[key]});await load()}catch(e){setError(e.message)}}
 async function delExam(id){if(!confirm('حذف الاختبار وكل أسئلته؟'))return;try{await adminDeleteExam(id);if(selected?.id===id)setSelected(null);await load()}catch(e){setError(e.message)}}
 async function addQuestion(e){e.preventDefault();if(!selected)return;const opts=q.options.map(x=>x.trim()).filter(Boolean);if(opts.length<2)return setError('أدخل خيارين على الأقل');if(!q.correct_answer||!opts.includes(q.correct_answer))return setError('حدد الإجابة الصحيحة من الخيارات');try{await adminAddQuestion({exam_id:selected.id,question_text:q.question_text.trim(),options:opts,correct_answer:q.correct_answer,points:Number(q.points)||1,order_number:Number(q.order_number)||1});setQ({question_text:'',options:['','','',''],correct_answer:'',points:1,order_number:(selected.exam_questions?.length||0)+2});setMessage('تمت إضافة السؤال');await load()}catch(e){setError(e.message)}}
 async function delQuestion(id){if(!confirm('حذف السؤال؟'))return;try{await adminDeleteQuestion(id);await load()}catch(e){setError(e.message)}}
 return <div dir={i18n.language?.startsWith("ar") ? "rtl" : "ltr"}><h1 className="text-3xl font-bold">اختبارات الدورة</h1><p className="mt-1 text-gray-500">{course?.title}</p>{message&&<div className="mt-4 rounded bg-green-50 p-3 text-green-700">{message}</div>}{error&&<div className="mt-4 rounded bg-red-50 p-3 text-red-700">{error}</div>}
 <div className="mt-6 grid gap-6 xl:grid-cols-[360px_1fr]"><section><form onSubmit={create} className="rounded-xl bg-white p-5 shadow"><h2 className="text-xl font-bold">إنشاء اختبار</h2><Input label="العنوان" value={form.title} onChange={v=>setForm({...form,title:v})}/><label className="mt-3 block"><span className="mb-1 block">الوصف</span><textarea className="w-full rounded border p-2" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><Input label="درجة النجاح %" type="number" value={form.passing_score} onChange={v=>setForm({...form,passing_score:v})}/><Input label="عدد المحاولات" type="number" value={form.max_attempts} onChange={v=>setForm({...form,max_attempts:v})}/></div><button className="mt-4 w-full rounded bg-[#08284d] py-2 font-bold text-white">إنشاء</button></form><div className="mt-4 space-y-3">{exams.map(ex=><button key={ex.id} onClick={()=>setSelected(ex)} className={`w-full rounded-xl border bg-white p-4 text-right ${selected?.id===ex.id?'border-orange-500':''}`}><div className="font-bold">{ex.title}</div><div className="mt-1 text-xs text-gray-500">{ex.exam_questions?.length||0} سؤال — {ex.is_published?'منشور':'مسودة'}</div></button>)}</div></section>
 <section>{selected?<div className="space-y-6"><div className="rounded-xl bg-white p-5 shadow"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl font-bold">{selected.title}</h2><p className="text-gray-500">نجاح {selected.passing_score}% — {selected.max_attempts} محاولات</p></div><div className="flex gap-2"><button onClick={()=>toggle(selected,'is_published')} className="rounded bg-green-600 px-3 py-2 text-white">{selected.is_published?'إلغاء النشر':'نشر'}</button><button onClick={()=>toggle(selected,'is_final')} className="rounded bg-slate-700 px-3 py-2 text-white">{selected.is_final?'نهائي ✓':'جعله نهائي'}</button><button onClick={()=>delExam(selected.id)} className="rounded bg-red-600 px-3 py-2 text-white">حذف</button></div></div></div>
 <form onSubmit={addQuestion} className="rounded-xl bg-white p-5 shadow"><h3 className="text-xl font-bold">إضافة سؤال</h3><Input label="نص السؤال" value={q.question_text} onChange={v=>setQ({...q,question_text:v})}/>{q.options.map((o,i)=><Input key={i} label={`الخيار ${i+1}`} value={o} onChange={v=>{const a=[...q.options];a[i]=v;setQ({...q,options:a})}}/>)}<label className="mt-3 block"><span className="mb-1 block">الإجابة الصحيحة</span><select className="w-full rounded border p-2" value={q.correct_answer} onChange={e=>setQ({...q,correct_answer:e.target.value})}><option value="">اختر</option>{q.options.filter(Boolean).map(o=><option key={o} value={o}>{o}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><Input label="النقاط" type="number" value={q.points} onChange={v=>setQ({...q,points:v})}/><Input label="الترتيب" type="number" value={q.order_number} onChange={v=>setQ({...q,order_number:v})}/></div><button className="mt-4 rounded bg-orange-500 px-5 py-2 font-bold text-white">إضافة السؤال</button></form>
 <div className="rounded-xl bg-white p-5 shadow"><h3 className="text-xl font-bold">الأسئلة</h3><div className="mt-4 space-y-3">{(selected.exam_questions||[]).sort((a,b)=>a.order_number-b.order_number).map((qq,i)=><div key={qq.id} className="rounded border p-3"><div className="flex justify-between gap-3"><b>{i+1}. {qq.question_text}</b><button onClick={()=>delQuestion(qq.id)} className="text-red-600">حذف</button></div><div className="mt-2 text-sm text-gray-500">الصحيحة: {qq.correct_answer}</div></div>)}</div></div>
 <div className="rounded-xl bg-white p-5 shadow"><h3 className="text-xl font-bold">نتائج الطلاب</h3><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2">الطالب</th><th>الدرجة</th><th>النتيجة</th><th>التاريخ</th></tr></thead><tbody>{attempts.filter(a=>a.exam_id===selected.id).map(a=><tr key={a.id} className="border-b"><td className="p-2">{a.profiles?.full_name||a.profiles?.email||a.user_id}</td><td>{a.score}%</td><td>{a.passed?'ناجح':'غير مجتاز'}</td><td>{new Date(a.submitted_at).toLocaleString('ar-SA')}</td></tr>)}</tbody></table></div></div>
 </div>:<div className="rounded-xl bg-white p-10 text-center text-gray-500">أنشئ أو اختر اختبارًا لإدارة الأسئلة.</div>}</section></div></div>}
function Input({label,type='text',value,onChange}){return <label className="mt-3 block"><span className="mb-1 block">{label}</span><input required className="w-full rounded border p-2" type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}