import {useEffect,useState} from "react";
import {FaCheck,FaClock} from "react-icons/fa";
import {getSchoolEmployees,getStaffAttendance,saveStaffAttendance} from "../../../services/schoolService";
const statuses=[["present","حاضر"],["late","متأخر"],["absent","غائب"],["leave","إجازة"],["remote","عن بعد"],["holiday","عطلة"]];
export default function StaffAttendance(){
 const[date,setDate]=useState(new Date().toISOString().slice(0,10)),[employees,setEmployees]=useState([]),[records,setRecords]=useState({}),[busy,setBusy]=useState(false);
 async function load(){const[e,a]=await Promise.all([getSchoolEmployees(),getStaffAttendance(date)]);setEmployees(e.filter(x=>x.status==="active"));const map={};for(const emp of e.filter(x=>x.status==="active")){const r=a.find(x=>x.employee_id===emp.id);map[emp.id]={employee_id:emp.id,status:r?.status||"present",check_in:r?.check_in?String(r.check_in).slice(0,5):"08:00",check_out:r?.check_out?String(r.check_out).slice(0,5):"16:00",late_minutes:String(r?.late_minutes||0),overtime_minutes:String(r?.overtime_minutes||0),note:r?.note||""}}setRecords(map)}
 useEffect(()=>{load().catch(e=>alert(e.message))},[date]);
 async function save(){try{setBusy(true);const n=await saveStaffAttendance(date,Object.values(records));alert(`تم حفظ حضور ${n} موظف`);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 return <div><h1 className="text-3xl font-extrabold text-[#12345b]">حضور الموظفين</h1><p className="mt-2 text-slate-500">الحضور، الغياب، التأخير والعمل الإضافي وربطه بالرواتب.</p><div className="academy-card mt-5 p-5"><input type="date" className="academy-input max-w-xs" value={date} onChange={e=>setDate(e.target.value)}/><div className="mt-5 space-y-3">{employees.map(emp=>{const r=records[emp.id]||{};return <div key={emp.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-bold text-orange-600">{emp.employee_no}</div><h3 className="font-extrabold text-[#12345b]">{emp.full_name_ar}</h3></div><div className="flex flex-wrap gap-2">{statuses.map(([k,l])=><button type="button" key={k} onClick={()=>setRecords(v=>({...v,[emp.id]:{...r,status:k}}))} className={`rounded-lg px-3 py-2 text-xs font-bold ${r.status===k?"bg-[#12345b] text-white":"bg-slate-100"}`}>{l}</button>)}</div></div><div className="mt-3 grid gap-3 md:grid-cols-4"><input type="time" className="academy-input" value={r.check_in||""} onChange={e=>setRecords(v=>({...v,[emp.id]:{...r,check_in:e.target.value}}))}/><input type="time" className="academy-input" value={r.check_out||""} onChange={e=>setRecords(v=>({...v,[emp.id]:{...r,check_out:e.target.value}}))}/><input type="number" min="0" className="academy-input" placeholder="دقائق التأخير" value={r.late_minutes||"0"} onChange={e=>setRecords(v=>({...v,[emp.id]:{...r,late_minutes:e.target.value}}))}/><input type="number" min="0" className="academy-input" placeholder="دقائق إضافية" value={r.overtime_minutes||"0"} onChange={e=>setRecords(v=>({...v,[emp.id]:{...r,overtime_minutes:e.target.value}}))}/></div></div>})}</div><button onClick={save} disabled={busy||!employees.length} className="academy-btn-primary mt-5 w-full"><FaCheck/>حفظ الحضور</button></div></div>}
