import {useEffect,useState} from "react";import {useTranslation} from "react-i18next";import {FaCheck,FaFileInvoice,FaRotate,FaXmark} from "react-icons/fa6";import {approveBankPayment,createReceiptSignedUrl,getAdminPayments,rejectBankPayment} from "../../services/paymentService";import {AdminPageHeader,AdminTable,Directional,StatusBadge} from "../../components/admin/AdminUI";
export default function Payments(){const{t,i18n}=useTranslation();const[p,setP]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[error,setError]=useState("");
 async function load(){try{setLoading(true);setError("");setP(await getAdminPayments())}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 async function receipt(x){try{const u=await createReceiptSignedUrl(x.receipt_path);if(u)window.open(u,"_blank","noopener,noreferrer")}catch(e){alert(e.message)}}
 async function approve(x){if(!confirm(`${t("admin.approve")} ${Number(x.amount).toFixed(2)} SAR?`))return;try{setBusy(x.id);await approveBankPayment(x.id);await load()}catch(e){alert(e.message)}finally{setBusy(null)}}
 async function reject(x){const note=prompt(t("admin.reject")+":","");if(note===null)return;if(!note.trim())return alert(t("admin.reject"));try{setBusy(x.id);await rejectBankPayment(x.id,note);await load()}catch(e){alert(e.message)}finally{setBusy(null)}}
 return <div><AdminPageHeader title={t("admin.payments")} description={t("admin.paymentsDesc")} actions={<button onClick={load} className="academy-btn-dark"><FaRotate/>{t("common.refresh")}</button>}/>{error&&<div className="mb-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}
 {loading?<div className="academy-card p-10 text-center">{t("common.loading")}</div>:<AdminTable minWidth="980px"><thead className="bg-[#08284d] text-white"><tr>{[t("common.date"),t("common.course"),t("admin.method"),t("common.amount"),t("common.status"),t("admin.reference"),t("common.actions")].map(x=><th key={x} className="p-3 text-start">{x}</th>)}</tr></thead><tbody>{p.map(x=><tr key={x.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="p-3"><Directional>{new Date(x.created_at).toLocaleString(i18n.language?.startsWith("ar")?"ar-SA":"en-US")}</Directional></td><td className="p-3 font-bold text-[#08284d]">{x.courses?.title||x.course_id}</td><td className="p-3">{x.method==="bank_transfer"?t("admin.bankTransfer"):"PayPal"}</td><td className="p-3"><Directional>{Number(x.amount).toFixed(2)} {x.currency}</Directional></td><td className="p-3"><StatusBadge status={x.status}/></td><td className="p-3"><Directional>{x.bank_reference||x.provider_order_id||"—"}</Directional></td><td className="p-3"><div className="flex gap-1.5">{x.receipt_path&&<Btn title={t("admin.receipt")} cls="bg-slate-100 text-slate-700" onClick={()=>receipt(x)}><FaFileInvoice/></Btn>}{x.method==="bank_transfer"&&x.status==="pending"&&<><Btn disabled={busy===x.id} title={t("admin.approve")} cls="bg-emerald-50 text-emerald-700" onClick={()=>approve(x)}><FaCheck/></Btn><Btn disabled={busy===x.id} title={t("admin.reject")} cls="bg-red-50 text-red-700" onClick={()=>reject(x)}><FaXmark/></Btn></>}</div></td></tr>)}{!p.length&&<tr><td colSpan="7" className="p-10 text-center text-slate-500">{t("common.noResults")}</td></tr>}</tbody></AdminTable>}</div>}
function Btn({title,cls,onClick,disabled,children}){return <button disabled={disabled} title={title} aria-label={title} onClick={onClick} className={`flex h-9 w-9 items-center justify-center rounded-lg disabled:opacity-40 ${cls}`}>{children}</button>}
