import {useEffect,useMemo,useState} from "react";
import {FaChalkboardTeacher,FaEdit,FaLink,FaPlus,FaSave,FaSearch,FaTimes} from "react-icons/fa";
import {getSchoolCore,getSchoolSubjects,getSchoolTeachers,getTeacherAssignments,saveSchoolTeacher,saveTeacherAssignment} from "../../../services/schoolService";

const fresh=()=>({id:null,employee_no:"",full_name_ar:"",full_name_en:"",gender:"",phone:"",email:"",qualification:"",specialization:"",auth_user_id:"",status:"active",hire_date:new Date().toISOString().slice(0,10),notes:""});
const assignFresh=()=>({id:null,teacher_id:"",academic_year_id:"",grade_level_id:"",curriculum_id:"",subject_id:"",class_section_id:"",is_primary_teacher:true,is_active:true});

export default function SchoolTeachers(){
 const[teachers,setTeachers]=useState([]),[assignments,setAssignments]=useState([]),[core,setCore]=useState(null),[subjects,setSubjects]=useState([]),[form,setForm]=useState(fresh()),[assign,setAssign]=useState(assignFresh()),[mode,setMode]=useState("teacher"),[search,setSearch]=useState(""),[saving,setSaving]=useState(false);
 async function load(){const[c,t,a,s]=await Promise.all([getSchoolCore(),getSchoolTeachers(),getTeacherAssignments(),getSchoolSubjects()]);setCore(c);setTeachers(t);setAssignments(a);setSubjects(s);setAssign(v=>({...v,academic_year_id:v.academic_year_id||c.years.find(x=>x.is_current)?.id||"",grade_level_id:v.grade_level_id||c.grades[0]?.id||"",curriculum_id:v.curriculum_id||c.curricula[0]?.id||"",subject_id:v.subject_id||s[0]?.id||""}))}
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 function editTeacher(t){setMode("teacher");setForm({id:t.id,employee_no:t.employee_no||"",full_name_ar:t.full_name_ar||"",full_name_en:t.full_name_en||"",gender:t.gender||"",phone:t.phone||"",email:t.email||"",qualification:t.qualification||"",specialization:t.specialization||"",auth_user_id:t.auth_user_id||"",status:t.status||"active",hire_date:t.hire_date||new Date().toISOString().slice(0,10),notes:t.notes||""});window.scrollTo({top:0,behavior:"smooth"})}
 async function saveTeacherForm(e){e.preventDefault();try{setSaving(true);const editing=!!form.id;await saveSchoolTeacher(form);setForm(fresh());await load();alert(editing?"تم تحديث بيانات المعلم":"تم إضافة المعلم")}catch(e){alert(e.message)}finally{setSaving(false)}}
 function editAssign(x){setMode("assign");setAssign({id:x.id,teacher_id:x.teacher_id,academic_year_id:x.academic_year_id,grade_level_id:x.grade_level_id,curriculum_id:x.curriculum_id,subject_id:x.subject_id,class_section_id:x.class_section_id||"",is_primary_teacher:x.is_primary_teacher!==false,is_active:x.is_active!==false});window.scrollTo({top:0,behavior:"smooth"})}
 function resetAssign(){setAssign({id:null,teacher_id:"",academic_year_id:core?.years.find(x=>x.is_current)?.id||"",grade_level_id:core?.grades[0]?.id||"",curriculum_id:core?.curricula[0]?.id||"",subject_id:subjects[0]?.id||"",class_section_id:"",is_primary_teacher:true,is_active:true})}
 async function saveAssign(e){e.preventDefault();try{setSaving(true);await saveTeacherAssignment(assign);const editing=!!assign.id;resetAssign();await load();alert(editing?"تم تحديث توزيع المادة":"تم حفظ توزيع المادة")}catch(e){alert(e.message)}finally{setSaving(false)}}
 const visible=useMemo(()=>teachers.filter(t=>[t.employee_no,t.full_name_ar,t.full_name_en,t.specialization,t.phone,t.email].filter(Boolean).join(" ").toLowerCase().includes(search.toLowerCase())),[teachers,search]);
 const sections=(core?.sections||[]).filter(x=>x.grade_level_id===assign.grade_level_id&&x.curriculum_id===assign.curriculum_id);

 return <div>
  <div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold text-[#12345b]">المعلمون وتوزيع المواد</h1><p className="mt-2 text-slate-500">إضافة وتعديل المعلمين وربطهم بالصفوف والمواد والفصول.</p></div><div className="flex gap-2"><button onClick={()=>{setMode("teacher");setForm(fresh())}} className={`rounded-xl px-4 py-2 font-bold ${mode==="teacher"?"bg-orange-500 text-white":"bg-white"}`}>المعلمون</button><button onClick={()=>setMode("assign")} className={`rounded-xl px-4 py-2 font-bold ${mode==="assign"?"bg-orange-500 text-white":"bg-white"}`}>توزيع مادة</button></div></div>
  <div className="grid gap-6 xl:grid-cols-[450px_1fr]">
   <div>{mode==="teacher"?<form onSubmit={saveTeacherForm} className="academy-card space-y-4 p-5"><div className="flex justify-between"><h2 className="font-extrabold text-[#12345b]">{form.id?"تعديل المعلم":"معلم جديد"}</h2>{form.id&&<button type="button" onClick={()=>setForm(fresh())}><FaTimes/></button>}</div><Field label="الاسم بالعربية"><input required className="academy-input" value={form.full_name_ar} onChange={e=>setForm({...form,full_name_ar:e.target.value})}/></Field><Field label="الاسم بالإنجليزية"><input className="academy-input" value={form.full_name_en} onChange={e=>setForm({...form,full_name_en:e.target.value})}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="التخصص"><input className="academy-input" value={form.specialization} onChange={e=>setForm({...form,specialization:e.target.value})}/></Field><Field label="المؤهل"><input className="academy-input" value={form.qualification} onChange={e=>setForm({...form,qualification:e.target.value})}/></Field></div><div className="grid gap-3 sm:grid-cols-2"><Field label="الجوال"><input dir="ltr" className="academy-input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="البريد"><input dir="ltr" type="email" className="academy-input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field></div><Field label="Auth User ID"><input dir="ltr" className="academy-input" value={form.auth_user_id} onChange={e=>setForm({...form,auth_user_id:e.target.value})}/></Field><Field label="الحالة"><select className="academy-input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">نشط</option><option value="inactive">غير نشط</option><option value="on_leave">إجازة</option><option value="terminated">منتهي</option></select></Field><Field label="ملاحظات"><textarea className="academy-input min-h-20" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><button disabled={saving} className="academy-btn-primary w-full">{form.id?<FaSave/>:<FaPlus/>}{form.id?"حفظ التعديلات":"حفظ المعلم"}</button></form>:
   <form onSubmit={saveAssign} className="academy-card space-y-4 p-5"><div className="flex justify-between"><h2 className="font-extrabold text-[#12345b]">{assign.id?"تعديل توزيع المادة":"توزيع المادة"}</h2>{assign.id&&<button type="button" onClick={resetAssign}><FaTimes/></button>}</div><Field label="المعلم"><select required className="academy-input" value={assign.teacher_id} onChange={e=>setAssign({...assign,teacher_id:e.target.value})}><option value="">اختر</option>{teachers.map(x=><option key={x.id} value={x.id}>{x.employee_no} — {x.full_name_ar}</option>)}</select></Field><Field label="العام"><select required className="academy-input" value={assign.academic_year_id} onChange={e=>setAssign({...assign,academic_year_id:e.target.value})}>{(core?.years||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="المستوى"><select required className="academy-input" value={assign.grade_level_id} onChange={e=>setAssign({...assign,grade_level_id:e.target.value,class_section_id:""})}>{(core?.grades||[]).map(x=><option key={x.id} value={x.id}>{x.name_ar} / {x.name_en}</option>)}</select></Field><Field label="المنهج"><select required className="academy-input" value={assign.curriculum_id} onChange={e=>setAssign({...assign,curriculum_id:e.target.value,class_section_id:""})}>{(core?.curricula||[]).map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></Field><Field label="المادة"><select required className="academy-input" value={assign.subject_id} onChange={e=>setAssign({...assign,subject_id:e.target.value})}>{subjects.map(x=><option key={x.id} value={x.id}>{x.name_ar} / {x.name_en}</option>)}</select></Field><Field label="الفصل"><select className="academy-input" value={assign.class_section_id} onChange={e=>setAssign({...assign,class_section_id:e.target.value})}><option value="">كل فصول المستوى</option>{sections.map(x=><option key={x.id} value={x.id}>{x.section_name}</option>)}</select></Field><label className="flex gap-2 font-bold"><input type="checkbox" checked={assign.is_active!==false} onChange={e=>setAssign({...assign,is_active:e.target.checked})}/>التوزيع نشط</label><button disabled={saving} className="academy-btn-dark w-full"><FaLink/>{assign.id?"حفظ التعديلات":"حفظ التوزيع"}</button></form>}</div>
   <div><div className="mb-4 flex items-center gap-2 rounded-2xl border bg-white px-3"><FaSearch className="text-slate-400"/><input className="w-full bg-transparent py-3 outline-none" value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث عن معلم..."/></div><div className="grid gap-4 md:grid-cols-2">{visible.map(t=>{const a=assignments.filter(x=>x.teacher_id===t.id);return <div key={t.id} className={`academy-card p-5 ${t.status!=="active"?"opacity-60":""}`}><div className="flex items-start justify-between"><div><div dir="ltr" className="text-xs font-bold text-orange-600">{t.employee_no}</div><h3 className="mt-1 text-lg font-extrabold text-[#12345b]">{t.full_name_ar}</h3><div className="text-sm text-slate-500">{t.specialization||t.qualification||"—"}</div></div><div className="flex gap-2"><button onClick={()=>editTeacher(t)} className="rounded-lg bg-orange-50 p-2 text-orange-600"><FaEdit/></button><FaChalkboardTeacher className="mt-2 text-2xl text-blue-600"/></div></div><div className="mt-4 border-t pt-3"><div className="text-xs font-extrabold text-slate-400">المواد المكلف بها</div><div className="mt-2 space-y-2">{a.map(x=><div key={x.id} className="flex items-center justify-between gap-2 rounded-xl bg-slate-50 p-3 text-xs"><span><b>{x.school_subjects?.name_ar}</b> — {x.school_grade_levels?.name_ar} {x.school_class_sections?.section_name?`/ ${x.school_class_sections.section_name}`:""}</span><button onClick={()=>editAssign(x)} className="text-orange-600"><FaEdit/></button></div>)}{!a.length&&<div className="text-sm text-slate-400">لا يوجد توزيع بعد.</div>}</div></div></div>})}</div></div>
  </div>
 </div>
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-sm font-bold text-slate-700">{label}</span>{children}</label>}
