import {useEffect,useState} from "react";
import {FaMoneyCheckAlt,FaPlay} from "react-icons/fa";
import {generateSchoolPayroll,getSchoolFinanceAccounts,getSchoolPayrollRuns,paySchoolPayroll} from "../../../services/schoolService";
export default function SchoolPayroll(){
 const[runs,setRuns]=useState([]),[accounts,setAccounts]=useState([]),[month,setMonth]=useState(new Date().toISOString().slice(0,7)+"-01"),[account,setAccount]=useState("");
 async function load(){const[r,a]=await Promise.all([getSchoolPayrollRuns(),getSchoolFinanceAccounts()]);setRuns(r);setAccounts(a);setAccount(v=>v||a[0]?.id||"")}
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 async function gen(){const n=await generateSchoolPayroll(month);alert(`تم إنشاء ${n} بند راتب`);await load()}
 async function pay(id){if(!confirm("تأكيد صرف كل رواتب هذا الشهر وتسجيلها كمصروف؟"))return;const n=await paySchoolPayroll(id,account);alert(`تم صرف ${n} راتب`);await load()}
 return <div><h1 className="text-3xl font-extrabold text-[#12345b]">الرواتب</h1><p className="mt-2 text-slate-500">إنشاء مسير شهري وصرفه وربطه آليًا بالمصروفات.</p><div className="academy-card mt-6 flex flex-wrap items-end gap-3 p-5"><Field l="شهر الرواتب"><input type="month" className="academy-input" value={month.slice(0,7)} onChange={e=>setMonth(e.target.value+"-01")}/></Field><button onClick={gen} className="academy-btn-primary"><FaPlay/>إنشاء المسير</button><Field l="حساب الصرف"><select className="academy-input" value={account} onChange={e=>setAccount(e.target.value)}>{accounts.map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></Field></div><div className="mt-5 space-y-4">{runs.map(r=>{const total=(r.school_payroll_items||[]).reduce((a,x)=>a+Number(x.net_salary||0),0);return <div key={r.id} className="academy-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-extrabold text-[#12345b]">{r.payroll_month.slice(0,7)}</h2><div className="text-sm text-slate-500">{(r.school_payroll_items||[]).length} موظف • {r.status}</div></div><div className="text-end"><div dir="ltr" className="text-2xl font-extrabold">{total.toFixed(2)} SAR</div>{r.status!=="paid"&&<button onClick={()=>pay(r.id)} className="academy-btn-dark mt-2"><FaMoneyCheckAlt/>صرف الرواتب</button>}</div></div><div className="mt-4 divide-y border-t">{(r.school_payroll_items||[]).map(x=><div key={x.id} className="flex justify-between py-3 text-sm"><span>{x.school_employees?.full_name_ar}</span><b dir="ltr">{Number(x.net_salary).toFixed(2)}</b></div>)}</div></div>})}</div></div>}
function Field({l,children}){return <label className="block"><span className="mb-1.5 block text-sm font-bold">{l}</span>{children}</label>}
