import {useEffect,useState} from "react";
import {addSchoolStudentAffairsNote,getSchoolAttendanceExcuses,getSchoolMonthlyAttendanceReport,getSchoolOperationalSetup,getSchoolStudentAffairsProfile,reviewSchoolAttendanceExcuse} from "../../../services/schoolService";
export default function SchoolStudentAffairs(){
 const[ops,setOps]=useState(null),[sectionId,setSectionId]=useState(""),[report,setReport]=useState([]),[excuses,setExcuses]=useState([]),[tab,setTab]=useState("report");
 const now=new Date();const[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState(now.getMonth()+1);
 const[selectedStudent,setSelectedStudent]=useState(""),[profile,setProfile]=useState(null),[note,setNote]=useState({note_type:"general",severity:"normal",title:"",note:"",action_taken:"",is_private:true});
 async function load(){const[o,e]=await Promise.all([getSchoolOperationalSetup(),getSchoolAttendanceExcuses()]);setOps(o);setExcuses(e);const sid=sectionId||o.sections?.[0]?.id||"";setSectionId(sid);if(sid)setReport(await getSchoolMonthlyAttendanceReport(sid,year,month))}
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 async function refresh(){setReport(await getSchoolMonthlyAttendanceReport(sectionId,year,month))}
 async function openStudent(id){setSelectedStudent(id);setProfile(await getSchoolStudentAffairsProfile(id));setTab("student")}
 async function saveNote(e){e.preventDefault();const row=report.find(x=>x.student_id===selectedStudent);await addSchoolStudentAffairsNote({...note,student_id:selectedStudent,enrollment_id:row?.enrollment_id||null});setProfile(await getSchoolStudentAffairsProfile(selectedStudent));setNote({note_type:"general",severity:"normal",title:"",note:"",action_taken:"",is_private:true})}
 async function review(id,status){await reviewSchoolAttendanceExcuse(id,status,prompt("ملاحظة المراجعة","")||"");await load()}
 return <div><h1 className="text-3xl font-extrabold text-[#12345b]">شؤون الطلاب والحضور</h1><div className="mt-5 flex gap-2">{[["report","تقرير الحضور"],["excuses","الأعذار"],["student","متابعة طالب"]].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-xl px-4 py-2 font-bold ${tab===k?"bg-[#12345b] text-white":"bg-white border"}`}>{l}</button>)}</div>
 {tab==="report"&&<><div className="academy-card mt-5 grid gap-3 p-5 md:grid-cols-4"><select className="academy-input" value={sectionId} onChange={e=>setSectionId(e.target.value)}>{(ops?.sections||[]).map(x=><option key={x.id} value={x.id}>{x.grade_ar} / {x.curriculum_ar} / {x.section_name}</option>)}</select><input type="number" className="academy-input" value={year} onChange={e=>setYear(e.target.value)}/><input type="number" min="1" max="12" className="academy-input" value={month} onChange={e=>setMonth(e.target.value)}/><button onClick={refresh} className="academy-btn-dark">تحديث التقرير</button></div><div className="academy-card mt-5 overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr className="bg-slate-50 text-right"><th className="p-3">الطالب</th><th>حاضر</th><th>غائب</th><th>متأخر</th><th>بعذر</th><th>النسبة</th><th></th></tr></thead><tbody>{report.map(x=><tr key={x.enrollment_id} className="border-t"><td className="p-3"><b>{x.student_name}</b></td><td>{x.summary?.present||0}</td><td>{x.summary?.absent||0}</td><td>{x.summary?.late||0}</td><td>{x.summary?.excused||0}</td><td>{x.summary?.attendance_rate||0}%</td><td><button onClick={()=>openStudent(x.student_id)} className="academy-btn-dark">متابعة</button></td></tr>)}</tbody></table></div></>}
 {tab==="excuses"&&<div className="mt-5 space-y-3">{excuses.map(x=><div key={x.id} className="academy-card p-5"><b>{x.school_enrollments?.school_students?.full_name_ar}</b><div className="mt-1 text-sm">{x.excuse_date} • {x.excuse_type} • {x.status}</div><p className="mt-2">{x.reason}</p>{x.status==="pending"&&<div className="mt-3 flex gap-2"><button onClick={()=>review(x.id,"approved")} className="academy-btn-primary">اعتماد</button><button onClick={()=>review(x.id,"rejected")} className="rounded-xl bg-red-50 px-4 py-2 font-bold text-red-600">رفض</button></div>}</div>)}</div>}
 {tab==="student"&&<div className="mt-5 grid gap-6 xl:grid-cols-[420px_1fr]"><form onSubmit={saveNote} className="academy-card space-y-3 p-5"><select className="academy-input" value={selectedStudent} onChange={e=>openStudent(e.target.value)}><option value="">اختر الطالب</option>{report.map(x=><option key={x.student_id} value={x.student_id}>{x.student_name}</option>)}</select><select className="academy-input" value={note.note_type} onChange={e=>setNote({...note,note_type:e.target.value})}>{["general","behavior","academic","attendance","health","parent_contact","achievement"].map(x=><option key={x}>{x}</option>)}</select><select className="academy-input" value={note.severity} onChange={e=>setNote({...note,severity:e.target.value})}>{["low","normal","high","critical","positive"].map(x=><option key={x}>{x}</option>)}</select><input required className="academy-input" placeholder="العنوان" value={note.title} onChange={e=>setNote({...note,title:e.target.value})}/><textarea required className="academy-input min-h-24" placeholder="الملاحظة" value={note.note} onChange={e=>setNote({...note,note:e.target.value})}/><textarea className="academy-input min-h-20" placeholder="الإجراء" value={note.action_taken} onChange={e=>setNote({...note,action_taken:e.target.value})}/><button disabled={!selectedStudent} className="academy-btn-primary">حفظ الملاحظة</button></form><div className="space-y-3">{(profile?.notes||[]).map(n=><div key={n.id} className="academy-card p-5"><div className="text-xs text-orange-600">{n.note_type} • {n.severity}</div><b>{n.title}</b><p className="mt-2">{n.note}</p></div>)}</div></div>}
 </div>}
