import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {useTranslation} from "react-i18next";
import MainLayout from "../layouts/MainLayout";
import {getInstructorDashboard} from "../services/proAcademyFinalService";
export default function InstructorDashboard(){
 const{i18n}=useTranslation();const ar=i18n.language?.startsWith("ar");const[d,setD]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{getInstructorDashboard().then(setD).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 return <MainLayout><main className="min-h-screen bg-[#f7f9fc] py-10"><div className="academy-container">{loading?<div className="academy-card p-10 text-center">Loading...</div>:error?<div className="academy-card p-8 text-red-700">{error}</div>:<><div className="rounded-[24px] bg-[#08284d] p-7 text-white"><div className="text-sm font-bold text-orange-300">{ar?"لوحة المدرب":"Instructor Dashboard"}</div><h1 className="mt-2 text-3xl font-extrabold">{d.instructor?.full_name}</h1><p className="mt-2 text-slate-200">{d.instructor?.title}</p></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{(d.courses||[]).map(c=><article key={c.id} className="academy-card p-5"><h2 className="font-extrabold text-[#08284d]">{c.title}</h2><div className="mt-4 grid grid-cols-2 gap-2 text-center text-sm"><M l={ar?"طلاب":"Students"} v={c.enrollments_count}/><M l={ar?"تقييم":"Rating"} v={Number(c.rating_average||0).toFixed(1)}/><M l={ar?"مراجعات":"Reviews"} v={c.reviews_count}/><M l={ar?"أسئلة مفتوحة":"Open Q&A"} v={c.open_questions}/></div><div className="mt-4 flex gap-2"><Link to={`/courses/${c.id}`} className="academy-btn-dark text-sm">{ar?"الدورة":"Course"}</Link><Link to={`/qa/${c.id}`} className="rounded-xl border px-3 py-2 text-sm font-bold">Q&A</Link></div></article>)}</div><section className="mt-8"><h2 className="academy-title text-2xl">{ar?"أحدث الأسئلة":"Recent Questions"}</h2><div className="mt-4 space-y-3">{(d.recent_questions||[]).map(q=><Link key={q.id} to={`/qa/${q.course_id}`} className="academy-card block p-4"><div className="text-xs font-bold text-orange-600">{q.course_title}</div><div className="mt-1 font-extrabold text-[#08284d]">{q.title}</div><div className="mt-1 text-sm text-slate-500">{q.student_name}</div></Link>)}</div></section></>}</div></main></MainLayout>
}
function M({l,v}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-xl font-extrabold text-[#08284d]">{v}</div></div>}
