import {useEffect,useMemo,useState} from "react";
import {FaBook,FaDownload,FaHeart,FaRegHeart,FaSearch} from "react-icons/fa";
import {getSchoolBookFavorites,getSchoolBooks,recordSchoolBookDownload,toggleSchoolBookFavorite} from "../../../services/schoolService";
const typeLabels={textbook:"كتاب الطالب",workbook:"كتاب النشاط",teacher_guide:"دليل المعلم",reference:"مرجع",worksheet:"ورقة عمل",other:"أخرى"};
export default function SchoolLibraryPortal(){
 const[rows,setRows]=useState([]),[favorites,setFavorites]=useState([]),[query,setQuery]=useState("");
 async function load(){const[b,f]=await Promise.all([getSchoolBooks({publishedOnly:true}),getSchoolBookFavorites()]);setRows(b);setFavorites(f)}
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 const visible=useMemo(()=>rows.filter(x=>{const q=query.trim().toLowerCase();return !q||[x.title_ar,x.title_en,x.school_subjects?.name_ar,x.school_grade_levels?.name_ar,x.school_curricula?.name_ar].filter(Boolean).join(" ").toLowerCase().includes(q)}),[rows,query]);
 async function fav(id){const current=favorites.includes(id);await toggleSchoolBookFavorite(id,current);setFavorites(v=>current?v.filter(x=>x!==id):[...v,id])}
 async function openBook(x){try{if(x.is_downloadable)await recordSchoolBookDownload(x.id)}catch{}window.open(x.file_url,"_blank","noopener,noreferrer")}
 return <div><h1 className="text-3xl font-extrabold text-[#12345b]">المكتبة الرقمية</h1><p className="mt-2 text-slate-500">كتبك وملفاتك الدراسية حسب المنهج والصف والمادة.</p><div className="mt-5 flex items-center gap-2 rounded-2xl border bg-white px-3"><FaSearch className="text-slate-400"/><input className="w-full bg-transparent py-3 outline-none" placeholder="بحث..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map(x=><div key={x.id} className="academy-card overflow-hidden"><div className="h-44 bg-slate-100">{x.cover_url?<img src={x.cover_url} className="h-full w-full object-cover" alt=""/>:<div className="flex h-full items-center justify-center text-5xl text-slate-300"><FaBook/></div>}</div><div className="p-5"><div className="flex justify-between gap-3"><div><div className="text-xs font-bold text-orange-600">{typeLabels[x.book_type]||x.book_type}</div><h2 className="mt-1 font-extrabold text-[#12345b]">{x.title_ar}</h2></div><button onClick={()=>fav(x.id)} className="text-xl text-red-500">{favorites.includes(x.id)?<FaHeart/>:<FaRegHeart/>}</button></div><div className="mt-2 text-xs text-slate-500">{x.school_grade_levels?.name_ar} • {x.school_subjects?.name_ar}</div><button onClick={()=>openBook(x)} className="academy-btn-primary mt-4 w-full"><FaDownload/>{x.is_downloadable?"فتح / تنزيل":"فتح"}</button></div></div>)}</div></div>
}
