import {useEffect,useState} from "react";
import {FaArrowDown,FaArrowUp,FaPlus,FaUndo} from "react-icons/fa";
import {adjustSchoolFinance,getSchoolFinanceAccounts,getSchoolFinanceSummary,getSchoolFinanceTransactions,reverseSchoolFinanceTransaction,saveSchoolExpense,saveSchoolIncome} from "../../../services/schoolService";
const today=()=>new Date().toISOString().slice(0,10);
export default function SchoolAccounting(){
 const[accounts,setAccounts]=useState([]),[tx,setTx]=useState([]),[summary,setSummary]=useState({}),[tab,setTab]=useState("dashboard"),[from,setFrom]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10)),[to,setTo]=useState(today());
 const[income,setIncome]=useState({income_date:today(),category:"",amount:"",account_id:"",reference_no:"",source:"",description:""}),[expense,setExpense]=useState({expense_date:today(),category:"",vendor:"",amount:"",account_id:"",reference_no:"",description:"",status:"paid"});
 async function load(){const[a,t,s]=await Promise.all([getSchoolFinanceAccounts(),getSchoolFinanceTransactions(),getSchoolFinanceSummary(from,to)]);setAccounts(a);setTx(t);setSummary(s);setIncome(v=>({...v,account_id:v.account_id||a[0]?.id||""}));setExpense(v=>({...v,account_id:v.account_id||a[0]?.id||""}))}
 useEffect(()=>{load().catch(e=>alert(e.message))},[from,to]);
 async function addIncome(e){e.preventDefault();await saveSchoolIncome(income);setIncome(v=>({...v,category:"",amount:"",reference_no:"",source:"",description:""}));await load()}
 async function addExpense(e){e.preventDefault();await saveSchoolExpense(expense);setExpense(v=>({...v,category:"",vendor:"",amount:"",reference_no:"",description:""}));await load()}
 async function reverse(id){const reason=prompt("سبب عكس القيد؟");if(!reason)return;await reverseSchoolFinanceTransaction(id,reason);await load()}
 return <div><h1 className="text-3xl font-extrabold text-[#12345b]">المالية والمحاسبة</h1><p className="mt-2 text-slate-500">التحصيل، الإيرادات، المصروفات، الرواتب والقيود المالية.</p><div className="mt-5 flex flex-wrap gap-2">{[["dashboard","الملخص"],["income","إيراد"],["expense","مصروف"],["ledger","القيود"]].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-xl px-4 py-2 font-bold ${tab===k?"bg-orange-500 text-white":"bg-white"}`}>{l}</button>)}</div>
 {tab==="dashboard"&&<><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["التحصيل",summary.collections],["إيرادات أخرى",summary.other_income],["المصروفات",summary.expenses],["الرواتب",summary.salaries],["الصافي",summary.net]].map(([l,v])=><div key={l} className="academy-card p-5"><div className="text-sm text-slate-500">{l}</div><div dir="ltr" className="mt-2 text-2xl font-extrabold text-[#12345b]">{Number(v||0).toFixed(2)} SAR</div></div>)}</div><div className="mt-4 flex gap-3"><input type="date" className="academy-input max-w-xs" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" className="academy-input max-w-xs" value={to} onChange={e=>setTo(e.target.value)}/></div></>}
 {tab==="income"&&<Form title="إيراد جديد" submit={addIncome}><Field l="التاريخ"><input type="date" className="academy-input" value={income.income_date} onChange={e=>setIncome({...income,income_date:e.target.value})}/></Field><Field l="التصنيف"><input required className="academy-input" value={income.category} onChange={e=>setIncome({...income,category:e.target.value})}/></Field><Field l="المبلغ"><input required type="number" className="academy-input" value={income.amount} onChange={e=>setIncome({...income,amount:e.target.value})}/></Field><Account accounts={accounts} value={income.account_id} set={v=>setIncome({...income,account_id:v})}/><button className="academy-btn-primary w-full"><FaArrowDown/>تسجيل الإيراد</button></Form>}
 {tab==="expense"&&<Form title="مصروف جديد" submit={addExpense}><Field l="التاريخ"><input type="date" className="academy-input" value={expense.expense_date} onChange={e=>setExpense({...expense,expense_date:e.target.value})}/></Field><Field l="التصنيف"><input required className="academy-input" value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}/></Field><Field l="المورد"><input className="academy-input" value={expense.vendor} onChange={e=>setExpense({...expense,vendor:e.target.value})}/></Field><Field l="المبلغ"><input required type="number" className="academy-input" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></Field><Account accounts={accounts} value={expense.account_id} set={v=>setExpense({...expense,account_id:v})}/><button className="academy-btn-dark w-full"><FaArrowUp/>تسجيل المصروف</button></Form>}
 {tab==="ledger"&&<div className="mt-5 space-y-3">{tx.map(x=><div key={x.id} className="academy-card flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="font-extrabold text-[#12345b]">{x.description}</div><div className="mt-1 text-xs text-slate-500">{x.transaction_date} • {x.transaction_type}</div></div><div className="flex items-center gap-3"><b dir="ltr" className={x.direction==="in"?"text-emerald-700":"text-red-700"}>{x.direction==="in"?"+":"-"}{Number(x.amount).toFixed(2)}</b>{x.transaction_type!=="reversal"&&<button onClick={()=>reverse(x.id)} className="rounded-lg bg-red-50 p-2 text-red-600"><FaUndo/></button>}</div></div>)}</div>}
 </div>}
function Form({title,submit,children}){return <form onSubmit={submit} className="academy-card mt-5 max-w-xl space-y-4 p-5"><h2 className="font-extrabold text-[#12345b]">{title}</h2>{children}</form>}
function Field({l,children}){return <label className="block"><span className="mb-1.5 block text-sm font-bold">{l}</span>{children}</label>}
function Account({accounts,value,set}){return <Field l="الحساب"><select className="academy-input" value={value} onChange={e=>set(e.target.value)}>{accounts.map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></Field>}
