import { useEffect,useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import MainLayout from '../layouts/MainLayout';
import { getCurrentUser,getEnrollment } from '../services/enrollmentService';
import { getLessonsByCourse,getLessonProgress } from '../services/lessonService';
import { getPublishedExamsForCourse,getMyExamAttempts } from '../services/examService';
import { getMyCertificates,issueCertificateIfEligible } from '../services/certificateService';
import { supabase } from '../services/supabase';

export default function CourseCompletion(){const {courseId}=useParams();const [state,setState]=useState(null),[loading,setLoading]=useState(true),[login,setLogin]=useState(false),[error,setError]=useState('');
 async function load(){try{const user=await getCurrentUser();if(!user){setLogin(true);return;}const enrollment=await getEnrollment(courseId,user.id);if(!enrollment)throw new Error('أنت غير مسجل في هذه الدورة');const [{data:course,error:ce},lessons,progress,exams,attempts,certs]=await Promise.all([supabase.from('courses').select('id,title').eq('id',courseId).single(),getLessonsByCourse(courseId),getLessonProgress(user.id,courseId),getPublishedExamsForCourse(courseId),getMyExamAttempts(courseId),getMyCertificates()]);if(ce)throw ce;const completed=new Set(progress.map(x=>x.lesson_id));const finalExams=exams.filter(e=>e.is_final);const examPassed=finalExams.length===0||finalExams.every(e=>attempts.some(a=>a.exam_id===e.id&&a.passed));let cert=certs.find(c=>c.course_id===courseId)||null;if(enrollment.progress===100&&examPassed&&!cert){try{await issueCertificateIfEligible(courseId);const refreshed=await getMyCertificates();cert=refreshed.find(c=>c.course_id===courseId)||null}catch{}}setState({course,enrollment,lessons,completed,exams,attempts,examPassed,cert});}catch(e){setError(e.message||'تعذر تحميل حالة الإكمال')}finally{setLoading(false)}}
 useEffect(()=>{load()},[courseId]);if(login)return <Navigate to="/login" replace/>;if(loading)return <MainLayout><div className="p-12 text-center">جاري التحميل...</div></MainLayout>;if(error)return <MainLayout><div className="m-8 rounded bg-red-50 p-4 text-red-700">{error}</div></MainLayout>;
 const s=state;const lessonsDone=s.lessons.length===0?0:s.completed.size;const ready=(s.enrollment.progress||0)===100&&s.examPassed;
 return <MainLayout><main dir="rtl" className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-5xl"><h1 className="text-3xl font-bold">إكمال الدورة</h1><p className="mt-2 text-gray-500">{s.course.title}</p><div className="mt-7 grid gap-5 md:grid-cols-3"><Card title="تقدم الدورة" value={`${s.enrollment.progress||0}%`} ok={(s.enrollment.progress||0)===100}/><Card title="الدروس المكتملة" value={`${lessonsDone}/${s.lessons.length}`} ok={s.lessons.length>0&&lessonsDone===s.lessons.length}/><Card title="الاختبار النهائي" value={s.exams.filter(e=>e.is_final).length? (s.examPassed?'مجتاز':'مطلوب'):'لا يوجد'} ok={s.examPassed}/></div><div className={`mt-7 rounded-2xl p-6 ${ready?'bg-green-50 text-green-900':'bg-amber-50 text-amber-900'}`}><h2 className="text-xl font-bold">{ready?'متطلبات الدورة مكتملة ✅':'متطلبات الإكمال غير مكتملة'}</h2><p className="mt-2">{ready?'أصبحت مؤهلاً للحصول على شهادة الدورة.':'أكمل جميع الدروس واجتز الاختبار النهائي إن وجد.'}</p><div className="mt-4 flex flex-wrap gap-3"><Link to={`/learn/${courseId}`} className="rounded bg-blue-700 px-4 py-2 text-white">الدروس</Link><Link to={`/exams/${courseId}`} className="rounded bg-purple-600 px-4 py-2 text-white">الاختبارات</Link>{s.cert&&<Link to={`/certificates/${s.cert.id}`} className="rounded bg-green-700 px-4 py-2 text-white">عرض الشهادة</Link>}</div></div></div></main></MainLayout>}
function Card({title,value,ok}){return <div className="rounded-2xl bg-white p-5 shadow-sm"><div className="text-sm text-gray-500">{title}</div><div className="mt-2 flex items-center justify-between"><div className="text-2xl font-bold">{value}</div><div className="text-2xl">{ok?'✅':'⏳'}</div></div></div>}
