import {Link} from "react-router-dom";import {useTranslation} from "react-i18next";import {FaArrowRight,FaBriefcase,FaCheckCircle,FaQuoteRight,FaRocket,FaUsers} from "react-icons/fa";import MainLayout from "../layouts/MainLayout";import Hero from "../components/Hero";import CourseSection from "../components/CourseSection";import Stats from "../components/Stats";import ProfessionalHomeSections from "../components/ProfessionalHomeSections";
const areas=[["📡","Telecom & Networks","الاتصالات والشبكات"],["▤","IT & Data Centers","تقنية المعلومات ومراكز البيانات"],["⚙","Engineering","الهندسة"],["✓","Quality & Accreditation","الجودة والاعتماد"],["▥","Planning & Project Management","التخطيط وإدارة المشاريع"],["♟","Consultancy","الاستشارات والحلول"],["⌂","ELV Systems","الأنظمة منخفضة التيار ELV"]];
export default function Home(){const{i18n}=useTranslation();const ar=i18n.language?.startsWith("ar");return <MainLayout><Hero/>
<section className="academy-section bg-white"><div className="academy-container"><div className="text-center"><span className="academy-eyebrow">{ar?"مجالات التعلم":"Learning Areas"}</span><h2 className="academy-title mt-3 text-3xl md:text-4xl">{ar?"تعلم المهارات التي يحتاجها سوق العمل":"Skills built for real-world work"}</h2><p className="mx-auto mt-3 max-w-3xl leading-8 text-slate-500">{ar?"مزيج من الاتصالات والتقنية والهندسة والجودة والتخطيط والاستشارات، وليس تخصصًا واحدًا فقط.":"A multidisciplinary academy spanning telecom, technology, engineering, quality, planning and consulting."}</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{areas.map(([icon,en,arabic])=><Link to={`/search?q=${encodeURIComponent(ar?arabic:en)}`} key={en} className="academy-card p-5 hover:-translate-y-1 hover:border-orange-200 hover:shadow-xl"><div className="text-3xl">{icon}</div><h3 className="mt-3 font-extrabold text-[#08284d]">{ar?arabic:en}</h3><div className="mt-3 text-xs font-bold text-orange-600">{ar?"استكشف الدورات":"Explore courses"} →</div></Link>)}</div></div></section>
<CourseSection/><ProfessionalHomeSections/>
<section className="academy-section bg-[#08284d] text-white"><div className="academy-container"><div className="grid gap-6 md:grid-cols-3"><Value icon={<FaBriefcase/>} title={ar?"خبرة عملية":"Practical Expertise"} text={ar?"محتوى مبني على خبرات ومشاريع حقيقية.":"Learning built around practical field experience."}/><Value icon={<FaRocket/>} title={ar?"تقدم قابل للقياس":"Measurable Progress"} text={ar?"اختبارات، تقدم، مسارات وشهادات موثقة.":"Assessments, progress, paths and verifiable certificates."}/><Value icon={<FaUsers/>} title={ar?"تعلم مع خبراء":"Learn with Experts"} text={ar?"ملفات مدربين، Q&A وجلسات مباشرة.":"Instructor profiles, Q&A and live sessions."}/></div></div></section>
<Stats/>
<section className="academy-section bg-[#f7f9fc]"><div className="academy-container"><div className="text-center"><span className="academy-eyebrow">{ar?"تجربة المتعلم":"Learner Experience"}</span><h2 className="academy-title mt-3 text-3xl">{ar?"من التسجيل إلى الشهادة في مسار واضح":"A clear journey from enrollment to certificate"}</h2></div><div className="mt-8 grid gap-5 md:grid-cols-3">{[["01",ar?"اختر ما يناسبك":"Choose your goal",ar?"ابحث حسب المجال والمدرب والمسار.":"Search by field, instructor and learning path."],["02",ar?"تعلم وطبّق":"Learn & practice",ar?"فيديو، ملاحظات، اختبارات وQ&A.":"Video, notes, assessments and Q&A."],["03",ar?"أثبت إنجازك":"Prove your achievement",ar?"شهادة قابلة للتحقق عبر QR.":"A QR-verifiable completion certificate."]].map(([n,t,d])=><div key={n} className="academy-card p-6"><div className="text-4xl font-black text-orange-100">{n}</div><h3 className="mt-2 text-xl font-extrabold text-[#08284d]">{t}</h3><p className="mt-2 text-sm leading-7 text-slate-500">{d}</p></div>)}</div></div></section>
<section className="pb-16 bg-[#f7f9fc]"><div className="academy-container rounded-[28px] bg-gradient-to-br from-[#08284d] to-[#0d3767] px-7 py-9 text-white shadow-xl md:flex md:items-center md:justify-between md:px-10"><div><span className="text-sm font-bold text-orange-300">{ar?"ابدأ اليوم":"Start today"}</span><h2 className="mt-2 text-2xl font-extrabold md:text-3xl">{ar?"ابنِ مسارك المهني مع بصمة النوابغ":"Build your professional path with Basmat Alnawabigh"}</h2><p className="mt-2 text-slate-200">{ar?"دورات متخصصة، تعلم مرن، وشهادات قابلة للتحقق.":"Specialized courses, flexible learning and verifiable certificates."}</p></div><div className="mt-5 flex gap-3 md:mt-0"><Link to="/register" className="academy-btn-primary">{ar?"إنشاء حساب":"Create Account"}</Link><Link to="/courses" className="rounded-xl border border-white/20 px-5 py-3 font-bold">{ar?"تصفح الدورات":"Browse Courses"}</Link></div></div></section>
</MainLayout>}
function Value({icon,title,text}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-6"><div className="text-2xl text-orange-300">{icon}</div><h3 className="mt-3 text-xl font-extrabold">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-300">{text}</p></div>}
