import {useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {useTranslation} from "react-i18next";
import {FaArchive,FaBan,FaCheck,FaEdit,FaTrash,FaUndo} from "react-icons/fa";
import {AdminCard,AdminPageHeader,AdminTable,Directional,StatusBadge} from "../../components/admin/AdminUI";
import {checkStudentPermanentDelete,getStudentAdminDetail,setStudentAdminStatus,updateStudentAdmin} from "../../services/studentAdminService";

export default function StudentDetails(){
 const{id}=useParams();const{i18n}=useTranslation();const ar=i18n.language?.startsWith("ar");
 const[d,setD]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[editing,setEditing]=useState(false),[form,setForm]=useState({});
 async function load(){try{setLoading(true);setError("");const x=await getStudentAdminDetail(id);setD(x);setForm(x.profile||{})}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[id]);
 async function save(e){e.preventDefault();try{await updateStudentAdmin(id,form);setEditing(false);await load()}catch(e){alert(e.message)}}
 async function status(s){const label=s==="active"?(ar?"إعادة تفعيل الطالب؟":"Reactivate student?"):s==="disabled"?(ar?"تعطيل الطالب؟":"Disable student?"):(ar?"أرشفة الطالب؟":"Archive student?");if(!confirm(label))return;try{await setStudentAdminStatus(id,s);await load()}catch(e){alert(e.message)}}
 async function deletion(){try{const x=await checkStudentPermanentDelete(id);alert(x.can_delete?(ar?"لا توجد سجلات مانعة، لكن الحذف النهائي لحساب Auth يجب أن يتم من Supabase Admin/API الموثوق. لم يتم حذف أي شيء.":"No linked blockers. Final Auth-user deletion must still be done through trusted Supabase Admin/API. Nothing was deleted."):(ar?`الحذف النهائي ممنوع حاليًا.\nدورات: ${x.enrollments}\nمدفوعات: ${x.payments}\nاختبارات: ${x.attempts}\nشهادات: ${x.certificates}`:`Permanent deletion blocked.\nEnrollments: ${x.enrollments}\nPayments: ${x.payments}\nAttempts: ${x.attempts}\nCertificates: ${x.certificates}`))}catch(e){alert(e.message)}}
 if(loading)return <AdminCard className="p-10 text-center">{ar?"جاري التحميل...":"Loading..."}</AdminCard>;if(error||!d)return <div className="rounded-xl bg-red-50 p-4 text-red-700">{error||"Not found"}</div>;
 const p=d.profile||{},statusValue=p.account_status||"active";
 return <div><AdminPageHeader title={p.full_name||p.email|| (ar?"ملف الطالب":"Student Profile")} description={ar?"إدارة كاملة للطالب وسجله الأكاديمي والمالي.":"Full student lifecycle, academic and financial record."} actions={<Link to="/admin/students" className="academy-btn-dark">{ar?"رجوع":"Back"}</Link>}/>
 <div className="grid gap-6 xl:grid-cols-[360px_1fr]"><div className="space-y-5"><AdminCard className="p-5 text-center"><div className="mx-auto flex h-28 w-28 items-center justify-center overflow-hidden rounded-full bg-orange-50 text-4xl font-extrabold text-orange-600">{p.avatar_url?<img src={p.avatar_url} className="h-full w-full object-cover"/>:(p.full_name||p.email||"S")[0]}</div><h2 className="mt-4 text-xl font-extrabold text-[#08284d]">{p.full_name||"—"}</h2><div className="mt-2"><StatusBadge status={statusValue}/></div><div className="mt-4 space-y-2 text-sm text-slate-500"><div><Directional>{p.email||"—"}</Directional></div><div><Directional>{p.phone||"—"}</Directional></div><div>{p.city||"—"}</div></div></AdminCard>
 <AdminCard className="p-5"><h3 className="font-extrabold text-[#08284d]">{ar?"إدارة الحساب":"Account Management"}</h3><div className="mt-4 grid gap-2">{statusValue!=="active"&&<Action icon={<FaUndo/>} text={ar?"إعادة التفعيل":"Reactivate"} cls="bg-emerald-50 text-emerald-700" onClick={()=>status("active")}/>} {statusValue==="active"&&<Action icon={<FaBan/>} text={ar?"تعطيل مؤقت":"Temporarily Disable"} cls="bg-amber-50 text-amber-700" onClick={()=>status("disabled")}/>} {statusValue!=="archived"&&<Action icon={<FaArchive/>} text={ar?"أرشفة":"Archive"} cls="bg-slate-100 text-slate-700" onClick={()=>status("archived")}/>}<Action icon={<FaTrash/>} text={ar?"فحص إمكانية الحذف النهائي":"Check Permanent Delete"} cls="bg-red-50 text-red-700" onClick={deletion}/></div><p className="mt-3 text-xs leading-6 text-slate-500">{ar?"الحذف النهائي لا ينفذ من المتصفح، ويتم منعه عند وجود سجلات أكاديمية أو مالية.":"Permanent deletion is never executed from the browser and is blocked when academic/financial records exist."}</p></AdminCard></div>
 <div className="space-y-6"><AdminCard className="p-5"><div className="flex items-center justify-between"><h3 className="font-extrabold text-[#08284d]">{ar?"بيانات الطالب":"Student Details"}</h3><button onClick={()=>setEditing(!editing)} className="rounded-xl bg-orange-50 px-3 py-2 font-bold text-orange-600"><FaEdit className="inline me-2"/>{ar?"تعديل":"Edit"}</button></div><form onSubmit={save} className="mt-4 grid gap-4 md:grid-cols-2"><Field label={ar?"الاسم":"Name"} value={form.full_name} disabled={!editing} onChange={v=>setForm({...form,full_name:v})}/><Field label={ar?"البريد":"Email"} value={p.email} disabled dir="ltr"/><Field label={ar?"الهاتف":"Phone"} value={form.phone} disabled={!editing} dir="ltr" onChange={v=>setForm({...form,phone:v})}/><Field label={ar?"المدينة":"City"} value={form.city} disabled={!editing} onChange={v=>setForm({...form,city:v})}/><label className="md:col-span-2"><span className="mb-1 block text-sm font-bold">{ar?"نبذة":"Bio"}</span><textarea disabled={!editing} className="academy-input min-h-24 disabled:bg-slate-50" value={form.bio||""} onChange={e=>setForm({...form,bio:e.target.value})}/></label><label className="md:col-span-2"><span className="mb-1 block text-sm font-bold">{ar?"ملاحظة الإدارة":"Admin Note"}</span><textarea disabled={!editing} className="academy-input min-h-20 disabled:bg-slate-50" value={form.admin_note||""} onChange={e=>setForm({...form,admin_note:e.target.value})}/></label>{editing&&<button className="academy-btn-primary md:col-span-2"><FaCheck/>{ar?"حفظ التعديلات":"Save Changes"}</button>}</form></AdminCard>
 <Tabs d={d} ar={ar}/></div></div></div>
}
function Tabs({d,ar}){const[tab,setTab]=useState("courses");const tabs=[["courses",ar?"الدورات":"Courses"],["payments",ar?"المدفوعات":"Payments"],["exams",ar?"الاختبارات":"Exams"],["certs",ar?"الشهادات":"Certificates"],["activity",ar?"الإشعارات":"Notifications"]];return <AdminCard className="overflow-hidden"><div className="flex overflow-x-auto border-b">{tabs.map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`shrink-0 px-5 py-4 text-sm font-bold ${tab===k?"border-b-2 border-orange-500 text-orange-600":"text-slate-500"}`}>{l}</button>)}</div><div className="p-5">{tab==="courses"&&<Courses rows={d.enrollments||[]} ar={ar}/>} {tab==="payments"&&<Payments rows={d.payments||[]} ar={ar}/>} {tab==="exams"&&<Exams rows={d.attempts||[]} ar={ar}/>} {tab==="certs"&&<Certs rows={d.certificates||[]} ar={ar}/>} {tab==="activity"&&<Activity rows={d.notifications||[]} ar={ar}/>}</div></AdminCard>}
function Courses({rows,ar}){return <Table heads={[ar?"الدورة":"Course",ar?"التقدم":"Progress",ar?"الحالة":"Status"]}>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3 font-bold">{x.course_title}</td><td className="p-3"><Directional>{Number(x.progress||0)}%</Directional></td><td className="p-3"><StatusBadge status={x.status}/></td></tr>)}</Table>}
function Payments({rows,ar}){return <Table heads={[ar?"الدورة":"Course",ar?"المبلغ":"Amount",ar?"الطريقة":"Method",ar?"الحالة":"Status"]}>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3">{x.course_title}</td><td className="p-3"><Directional>{Number(x.amount||0).toFixed(2)} SAR</Directional></td><td className="p-3">{x.method}</td><td className="p-3"><StatusBadge status={x.status}/></td></tr>)}</Table>}
function Exams({rows,ar}){return <Table heads={[ar?"الاختبار":"Exam",ar?"الدورة":"Course",ar?"النتيجة":"Score",ar?"الحالة":"Result"]}>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3">{x.exam_title}</td><td className="p-3">{x.course_title}</td><td className="p-3"><Directional>{x.score}%</Directional></td><td className="p-3 font-bold">{x.passed?(ar?"ناجح":"Passed"):(ar?"غير ناجح":"Not Passed")}</td></tr>)}</Table>}
function Certs({rows,ar}){return <Table heads={[ar?"الدورة":"Course",ar?"رقم الشهادة":"Certificate No.",ar?"الحالة":"Status"]}>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3">{x.course_title}</td><td className="p-3"><Directional>{x.certificate_number}</Directional></td><td className="p-3"><StatusBadge status={x.status||"active"}/></td></tr>)}</Table>}
function Activity({rows,ar}){return <div className="space-y-3">{rows.map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><b>{x.title}</b><Directional>{new Date(x.created_at).toLocaleDateString()}</Directional></div><p className="mt-1 text-sm text-slate-600">{x.message}</p></div>)}{!rows.length&&<Empty ar={ar}/>}</div>}
function Table({heads,children}){return <AdminTable minWidth="650px"><thead className="bg-[#08284d] text-white"><tr>{heads.map(x=><th key={x} className="p-3 text-start">{x}</th>)}</tr></thead><tbody>{children}</tbody></AdminTable>}
function Empty({ar}){return <div className="p-8 text-center text-slate-500">{ar?"لا توجد بيانات.":"No data."}</div>}
function Field({label,value,onChange,disabled,dir}){return <label><span className="mb-1 block text-sm font-bold">{label}</span><input dir={dir} disabled={disabled} className="academy-input disabled:bg-slate-50" value={value||""} onChange={e=>onChange?.(e.target.value)}/></label>}
function Action({icon,text,cls,onClick}){return <button onClick={onClick} className={`flex items-center gap-2 rounded-xl px-4 py-3 text-start text-sm font-bold ${cls}`}>{icon}{text}</button>}
