import {useEffect,useMemo,useState} from "react";
import {FaCheck,FaClipboardCheck} from "react-icons/fa";
import {getAttendanceSessions,getClassActiveEnrollments,getSchoolCore,getSchoolSubjects,saveSchoolAttendance} from "../../../services/schoolService";
const statuses=[["present","حاضر"],["absent","غائب"],["late","متأخر"],["excused","بعذر"]];
export default function SchoolAttendance(){
 const[core,setCore]=useState(null),[subjects,setSubjects]=useState([]),[sessions,setSessions]=useState([]),[classId,setClassId]=useState(""),[subjectId,setSubjectId]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[period,setPeriod]=useState("1"),[students,setStudents]=useState([]),[records,setRecords]=useState({}),[busy,setBusy]=useState(false);
 async function init(){const[c,s,se]=await Promise.all([getSchoolCore(),getSchoolSubjects(),getAttendanceSessions()]);setCore(c);setSubjects(s);setSessions(se);setClassId(v=>v||c.sections[0]?.id||"");setSubjectId(v=>v||s[0]?.id||"")}
 useEffect(()=>{init().catch(e=>alert(e.message))},[]);
 useEffect(()=>{if(!classId){setStudents([]);return}getClassActiveEnrollments(classId).then(rows=>{setStudents(rows);setRecords(Object.fromEntries(rows.map(e=>[e.id,{status:"present",note:""}]))) }).catch(e=>alert(e.message))},[classId]);
 async function save(){try{setBusy(true);await saveSchoolAttendance({class_section_id:classId,subject_id:subjectId,attendance_date:date,period_no:period,records:students.map(e=>({enrollment_id:e.id,status:records[e.id]?.status||"present",note:records[e.id]?.note||""}))});alert("تم حفظ الحضور");await init()}catch(e){alert(e.message)}finally{setBusy(false)}}
 return <div><h1 className="text-3xl font-extrabold text-[#12345b]">الحضور والغياب</h1><p className="mt-2 text-slate-500">تسجيل الحضور حسب الفصل والمادة والحصة.</p><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_420px]"><div className="academy-card p-5"><div className="grid gap-3 md:grid-cols-4"><select className="academy-input" value={classId} onChange={e=>setClassId(e.target.value)}>{(core?.sections||[]).map(x=><option key={x.id} value={x.id}>{x.school_grade_levels?.name_ar} / {x.section_name}</option>)}</select><select className="academy-input" value={subjectId} onChange={e=>setSubjectId(e.target.value)}>{subjects.map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select><input type="date" className="academy-input" value={date} onChange={e=>setDate(e.target.value)}/><input type="number" min="1" className="academy-input" value={period} onChange={e=>setPeriod(e.target.value)}/></div><div className="mt-5 space-y-3">{students.map(e=><div key={e.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div dir="ltr" className="text-xs font-bold text-orange-600">{e.school_students?.student_no}</div><h3 className="font-extrabold text-[#12345b]">{e.school_students?.full_name_ar}</h3></div><div className="flex flex-wrap gap-2">{statuses.map(([k,l])=><button type="button" key={k} onClick={()=>setRecords(r=>({...r,[e.id]:{...(r[e.id]||{}),status:k}}))} className={`rounded-lg px-3 py-2 text-xs font-bold ${records[e.id]?.status===k?"bg-[#12345b] text-white":"bg-slate-100"}`}>{l}</button>)}</div></div></div>)}{!students.length&&<div className="p-8 text-center text-slate-400">لا يوجد طلاب في الفصل.</div>}</div><button disabled={busy||!students.length} onClick={save} className="academy-btn-primary mt-5 w-full"><FaCheck/>حفظ الحضور</button></div><div><h2 className="mb-3 font-extrabold text-[#12345b]">آخر جلسات الحضور</h2><div className="space-y-3">{sessions.slice(0,15).map(x=><div key={x.id} className="academy-card p-4"><div className="flex items-start justify-between"><div><b>{x.school_class_sections?.school_grade_levels?.name_ar} / {x.school_class_sections?.section_name}</b><div className="mt-1 text-sm text-slate-500">{x.school_subjects?.name_ar||"حضور عام"}</div></div><FaClipboardCheck className="text-emerald-600"/></div><div dir="ltr" className="mt-3 text-xs text-slate-400">{x.attendance_date}</div><div className="mt-2 text-xs font-bold text-orange-600">{(x.school_attendance_records||[]).length} طالب</div></div>)}</div></div></div></div>}
