import {useEffect,useState} from "react";
import {FaCheck,FaPlus,FaTimes} from "react-icons/fa";
import {getLeaveRequests,getLeaveTypes,getSchoolEmployees,reviewLeaveRequest,saveLeaveRequest} from "../../../services/schoolService";
export default function SchoolLeave(){
 const[employees,setEmployees]=useState([]),[types,setTypes]=useState([]),[rows,setRows]=useState([]),[form,setForm]=useState({employee_id:"",leave_type_id:"",starts_on:new Date().toISOString().slice(0,10),ends_on:new Date().toISOString().slice(0,10),reason:"",attachment_url:""});
 async function load(){const[e,t,r]=await Promise.all([getSchoolEmployees(),getLeaveTypes(),getLeaveRequests()]);setEmployees(e);setTypes(t);setRows(r);setForm(v=>({...v,employee_id:v.employee_id||e[0]?.id||"",leave_type_id:v.leave_type_id||t[0]?.id||""}))}
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 async function save(e){e.preventDefault();try{await saveLeaveRequest(form);setForm(v=>({...v,reason:"",attachment_url:""}));await load();alert("تم تسجيل طلب الإجازة")}catch(e){alert(e.message)}}
 async function review(id,status){const note=prompt("ملاحظة الإدارة (اختياري)")||"";await reviewLeaveRequest(id,status,note);await load()}
 return <div><h1 className="text-3xl font-extrabold text-[#12345b]">الإجازات</h1><p className="mt-2 text-slate-500">طلبات الإجازات والموافقة والرفض.</p><div className="mt-6 grid gap-6 xl:grid-cols-[430px_1fr]"><form onSubmit={save} className="academy-card space-y-4 p-5"><h2 className="font-extrabold text-[#12345b]">طلب إجازة</h2><Field l="الموظف"><select className="academy-input" value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})}>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name_ar}</option>)}</select></Field><Field l="نوع الإجازة"><select className="academy-input" value={form.leave_type_id} onChange={e=>setForm({...form,leave_type_id:e.target.value})}>{types.map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field l="من"><input type="date" className="academy-input" value={form.starts_on} onChange={e=>setForm({...form,starts_on:e.target.value})}/></Field><Field l="إلى"><input type="date" className="academy-input" value={form.ends_on} onChange={e=>setForm({...form,ends_on:e.target.value})}/></Field></div><Field l="السبب"><textarea className="academy-input min-h-24" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></Field><button className="academy-btn-primary w-full"><FaPlus/>تسجيل الطلب</button></form><div className="space-y-3">{rows.map(x=><div key={x.id} className="academy-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-extrabold text-[#12345b]">{x.school_employees?.full_name_ar}</h3><div className="mt-1 text-sm text-slate-500">{x.school_leave_types?.name_ar} • {x.starts_on} → {x.ends_on} • {x.days_count} يوم</div></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{x.status}</span></div>{x.status==="pending"&&<div className="mt-4 flex gap-2"><button onClick={()=>review(x.id,"approved")} className="academy-btn-primary"><FaCheck/>موافقة</button><button onClick={()=>review(x.id,"rejected")} className="academy-btn-dark"><FaTimes/>رفض</button></div>}</div>)}</div></div></div>}
function Field({l,children}){return <label className="block"><span className="mb-1.5 block text-sm font-bold">{l}</span>{children}</label>}
