import { useEffect,useMemo,useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import MainLayout from '../layouts/MainLayout';
import { getExamForStudent, submitExam } from '../services/examService';
import { issueCertificateIfEligible } from '../services/certificateService';
import { supabase } from '../services/supabase';
import { hasCourseCertificate } from '../services/courseCompletionService';

export default function ExamAttempt(){const {examId}=useParams();const [exam,setExam]=useState(null),[answers,setAnswers]=useState({}),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[result,setResult]=useState(null),[login,setLogin]=useState(false),[error,setError]=useState(''),[certifiedCourseId,setCertifiedCourseId]=useState(null);
 useEffect(()=>{(async()=>{try{const {data:{session}}=await supabase.auth.getSession();if(!session?.user){setLogin(true);return;}const loaded=await getExamForStudent(examId);setExam(loaded);if(loaded?.course_id&&await hasCourseCertificate(session.user.id,loaded.course_id)){setCertifiedCourseId(loaded.course_id);}}catch(e){setError(e.message||'تعذر تحميل الاختبار')}finally{setLoading(false)}})()},[examId]);
 const answered=useMemo(()=>Object.keys(answers).length,[answers]); if(login)return <Navigate to="/login" replace/>;
 async function submit(e){e.preventDefault();if(!exam)return;if(answered<exam.questions.length&&!confirm('لم تجب على كل الأسئلة. هل تريد التسليم؟'))return;try{setSubmitting(true);const r=await submitExam(exam.id,answers);setResult(r);if(r?.passed){try{await issueCertificateIfEligible(exam.course_id)}catch{}}}catch(e){setError(e.message||'تعذر تسليم الاختبار')}finally{setSubmitting(false)}}
 if(certifiedCourseId)return <MainLayout><main dir="rtl" className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-2xl rounded-2xl bg-white p-8 text-center shadow"><div className="text-5xl">🏆</div><h1 className="mt-4 text-2xl font-bold">هذه الدورة مكتملة</h1><p className="mt-3 text-gray-600">تم إصدار شهادتك بالفعل، لذلك لا تحتاج إلى إعادة الاختبار.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link to={`/learn/${certifiedCourseId}`} className="rounded-lg bg-blue-700 px-5 py-2 font-bold text-white">مراجعة الدورة</Link><Link to="/certificates" className="rounded-lg bg-green-600 px-5 py-2 font-bold text-white">عرض الشهادة</Link></div></div></main></MainLayout>;
 return <MainLayout><main dir="rtl" className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-4xl">{loading?<p>جاري التحميل...</p>:result?<div className="rounded-2xl bg-white p-8 text-center shadow"><div className="text-6xl">{result.passed?'🎉':'📝'}</div><h1 className="mt-4 text-3xl font-bold">{result.passed?'تم اجتياز الاختبار':'لم تحقق درجة النجاح'}</h1><p className="mt-4 text-xl">درجتك: <b>{result.score}%</b></p><p className="mt-2 text-gray-500">درجة النجاح: {result.passing_score}% — المحاولة {result.attempt_number}/{result.max_attempts}</p><div className="mt-6 flex justify-center gap-3"><Link to={`/exams/${result.course_id}`} className="rounded bg-blue-700 px-5 py-2 text-white">العودة للاختبارات</Link>{result.passed&&<Link to="/certificates" className="rounded bg-green-600 px-5 py-2 text-white">شهاداتي</Link>}</div></div>:exam?<form onSubmit={submit}><div className="rounded-2xl bg-white p-6 shadow"><h1 className="text-3xl font-bold">{exam.title}</h1><p className="mt-2 text-gray-500">{exam.description}</p><p className="mt-3 text-sm">الأسئلة: {exam.questions.length} — درجة النجاح: {exam.passing_score}% — المتبقي من المحاولات: {exam.remaining_attempts}</p></div><div className="mt-6 space-y-5">{exam.questions.map((q,i)=><div key={q.id} className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold">{i+1}. {q.question_text}</h2><div className="mt-4 space-y-2">{q.options.map(opt=><label key={opt} className={`flex cursor-pointer items-center gap-3 rounded-lg border p-3 ${answers[q.id]===opt?'border-orange-500 bg-orange-50':''}`}><input type="radio" name={q.id} value={opt} checked={answers[q.id]===opt} onChange={()=>setAnswers({...answers,[q.id]:opt})}/><span>{opt}</span></label>)}</div></div>)}</div>{error&&<div className="mt-5 rounded bg-red-50 p-3 text-red-700">{error}</div>}<button disabled={submitting} className="mt-6 rounded-lg bg-orange-500 px-8 py-3 font-bold text-white disabled:opacity-50">{submitting?'جارٍ التصحيح...':'تسليم الاختبار'}</button></form>:<div className="rounded bg-red-50 p-4 text-red-700">{error||'الاختبار غير متاح'}</div>}</div></main></MainLayout>}
