import { useEffect,useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import MainLayout from '../layouts/MainLayout';
import { getCurrentUser, getEnrollment } from '../services/enrollmentService';
import { getPublishedExamsForCourse, getMyExamAttempts } from '../services/examService';
import { hasCourseCertificate } from '../services/courseCompletionService';

export default function Exams(){const {courseId}=useParams();const [items,setItems]=useState([]),[attempts,setAttempts]=useState([]),[loading,setLoading]=useState(true),[login,setLogin]=useState(false),[denied,setDenied]=useState(false),[error,setError]=useState(''),[certified,setCertified]=useState(false);
 useEffect(()=>{(async()=>{try{const u=await getCurrentUser();if(!u){setLogin(true);return;}const en=await getEnrollment(courseId,u.id);if(!en||en.status==='cancelled'){setDenied(true);return;}const [e,a,cert]=await Promise.all([getPublishedExamsForCourse(courseId),getMyExamAttempts(courseId),hasCourseCertificate(u.id,courseId)]);setItems(e);setAttempts(a);setCertified(cert);}catch(e){setError(e.message||'تعذر تحميل الاختبارات')}finally{setLoading(false)}})()},[courseId]);
 if(login)return <Navigate to="/login" replace/>;return <MainLayout><main dir="rtl" className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-5xl"><h1 className="text-3xl font-bold">اختبارات الدورة</h1>{certified&&<div className="mt-5 rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">الدورة مكتملة والشهادة صادرة. يمكنك مراجعة المحتوى، ولا تحتاج إلى إعادة الاختبارات.</div>}{loading&&<p className="mt-6">جاري التحميل...</p>}{denied&&<div className="mt-6 rounded bg-red-50 p-4 text-red-700">يجب أن تكون مسجلاً في الدورة.</div>}{error&&<div className="mt-6 rounded bg-red-50 p-4 text-red-700">{error}</div>}<div className="mt-6 space-y-4">{items.map(ex=>{const ea=attempts.filter(a=>a.exam_id===ex.id);const passed=ea.some(a=>a.passed);return <div key={ex.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{ex.title}</h2><p className="mt-1 text-gray-500">درجة النجاح {ex.passing_score}% — المحاولات {ea.length}/{ex.max_attempts}</p></div>{certified ? <span className="rounded-lg bg-emerald-100 px-5 py-2 font-bold text-emerald-700">مكتمل — لا إعادة للاختبار ✓</span> : passed ? <span className="rounded-lg bg-green-100 px-5 py-2 font-bold text-green-700">تم الاجتياز ✓</span> : ea.length >= ex.max_attempts ? <span className="rounded-lg bg-gray-200 px-5 py-2 font-bold text-gray-600">انتهت المحاولات</span> : <Link to={`/exam/${ex.id}`} className="rounded-lg bg-blue-700 px-5 py-2 font-bold text-white">ابدأ الاختبار</Link>}</div>{ea[0]&&<p className="mt-3 text-sm">آخر نتيجة: <b>{ea[0].score}%</b> — {ea[0].passed?'ناجح ✅':'غير مجتاز'}</p>}</div>})}{!loading&&!items.length&&<div className="rounded-2xl bg-white p-8 text-center text-gray-500">لا توجد اختبارات منشورة لهذه الدورة.</div>}</div></div></main></MainLayout>}
