import {useEffect,useState} from "react";
import {Link,useSearchParams} from "react-router-dom";
import {useTranslation} from "react-i18next";
import MainLayout from "../layouts/MainLayout";
import {globalSearch} from "../services/finalProductionService";
export default function Search(){
 const[sp,setSp]=useSearchParams();const initial=sp.get("q")||"";const[q,setQ]=useState(initial),[data,setData]=useState({courses:[],paths:[],instructors:[]}),[loading,setLoading]=useState(false),[error,setError]=useState("");const{i18n}=useTranslation();const ar=i18n.language?.startsWith("ar");
 async function run(term){if(!term.trim()){setData({courses:[],paths:[],instructors:[]});return}try{setLoading(true);setError("");setData(await globalSearch(term))}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{run(initial)},[initial]);
 function submit(e){e.preventDefault();setSp({q:q.trim()})}
 return <MainLayout><main className="min-h-screen bg-[#f7f9fc] py-10"><div className="academy-container"><h1 className="academy-title text-3xl">{ar?"البحث":"Search"}</h1><form onSubmit={submit} className="mt-5 flex gap-2"><input autoFocus className="academy-input" value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?"ابحث عن دورة أو مدرب أو مسار":"Search courses, instructors or paths"}/><button className="academy-btn-primary">{ar?"بحث":"Search"}</button></form>{error&&<div className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}{loading?<div className="academy-card mt-6 p-10 text-center">Loading...</div>:<div className="mt-8 space-y-8"><Section title={ar?"الدورات":"Courses"} items={data.courses} render={x=><Link to={`/courses/${x.id}`} className="academy-card block overflow-hidden"><img src={x.image||"https://placehold.co/640x360?text=Course"} className="aspect-video w-full object-cover"/><div className="p-4"><h3 className="font-extrabold text-[#08284d]">{x.title}</h3><p className="mt-1 text-sm text-slate-500">{x.instructor}</p></div></Link>}/><Section title={ar?"المسارات":"Learning Paths"} items={data.paths} render={x=><Link to={`/paths/${x.id}`} className="academy-card block p-5"><h3 className="font-extrabold text-[#08284d]">{x.title}</h3><p className="mt-2 line-clamp-2 text-sm text-slate-500">{x.description}</p></Link>}/><Section title={ar?"المدربون":"Instructors"} items={data.instructors} render={x=><Link to={`/instructors/${x.id}`} className="academy-card flex items-center gap-4 p-4"><img src={x.photo_url||"https://placehold.co/120x120?text=I"} className="h-16 w-16 rounded-full object-cover"/><div><h3 className="font-extrabold text-[#08284d]">{x.full_name}</h3><p className="text-sm text-slate-500">{x.title}</p></div></Link>}/></div>}</div></main></MainLayout>
}
function Section({title,items,render}){return <section><h2 className="academy-title text-2xl">{title}</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{(items||[]).map(x=><div key={x.id}>{render(x)}</div>)}{!items?.length&&<div className="text-sm text-slate-400">No results</div>}</div></section>}
