import {useEffect,useMemo,useState} from "react";
import {Link,Navigate} from "react-router-dom";
import {useTranslation} from "react-i18next";
import {FaBookOpen,FaBell,FaCertificate,FaCreditCard,FaHeart,FaVideo} from "react-icons/fa";
import MainLayout from "../layouts/MainLayout";
import {getCurrentUser,getMyEnrollments} from "../services/enrollmentService";
import {getMyCertificates} from "../services/certificateService";
import {supabase} from "../services/supabase";
import {getMyLiveSessions} from "../services/professionalAcademyService";

export default function StudentDashboard(){
 const {i18n}=useTranslation();const ar=i18n.language?.startsWith("ar");const[loading,setLoading]=useState(true),[login,setLogin]=useState(false),[enrollments,setEnrollments]=useState([]),[certs,setCerts]=useState([]),[notifications,setNotifications]=useState(0),[payments,setPayments]=useState(0),[liveCount,setLiveCount]=useState(0);
 useEffect(()=>{(async()=>{try{const u=await getCurrentUser();if(!u){setLogin(true);return}const [e,c,n,p,live]=await Promise.all([getMyEnrollments(u.id),getMyCertificates(),supabase.from("notifications").select("id",{count:"exact",head:true}).eq("user_id",u.id).eq("is_read",false),supabase.from("payments").select("id",{count:"exact",head:true}).eq("user_id",u.id),getMyLiveSessions()]);setEnrollments(e||[]);setCerts(c||[]);setNotifications(n.count||0);setPayments(p.count||0);setLiveCount((live||[]).filter(x=>x.status==="scheduled"&&new Date(x.start_at)>=new Date()).length)}finally{setLoading(false)}})()},[]);
 const continueItems=useMemo(()=>enrollments.filter(x=>Number(x.progress||0)<100).slice(0,4),[enrollments]);
 if(login)return <Navigate to="/login" replace/>;
 return <MainLayout><main className="min-h-screen bg-[#f7f9fc] py-10"><div className="academy-container"><div className="rounded-[24px] bg-[#08284d] p-7 text-white"><p className="text-sm font-bold text-orange-300">Basmat Alnawabigh Academy</p><h1 className="mt-2 text-3xl font-extrabold">{ar?"مرحبًا بك في لوحة التعلم":"Welcome to your learning dashboard"}</h1><p className="mt-2 text-slate-200">{ar?"تابع تعلمك، اختباراتك وشهاداتك من مكان واحد.":"Continue learning, exams and certificates from one place."}</p></div>
 {loading?<div className="academy-card mt-6 p-10 text-center">{ar?"جاري التحميل...":"Loading..."}</div>:<>
 <div className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-6"><Metric icon={<FaBookOpen/>} label={ar?"دوراتي":"My Courses"} value={enrollments.length} to="/my-courses"/><Metric icon={<FaHeart/>} label={ar?"الرغبات":"Wishlist"} value="—" to="/wishlist"/><Metric icon={<FaBell/>} label={ar?"إشعارات جديدة":"Unread Alerts"} value={notifications} to="/notifications"/><Metric icon={<FaCreditCard/>} label={ar?"المدفوعات":"Payments"} value={payments} to="/my-payments"/><Metric icon={<FaVideo/>} label={ar?"جلسات قادمة":"Upcoming Live"} value={liveCount} to="/live-sessions"/><Metric icon={<FaCertificate/>} label={ar?"الشهادات":"Certificates"} value={certs.length} to="/certificates"/></div>
 <div className="mt-5 flex flex-wrap gap-3"><Link to="/cart" className="rounded-xl border bg-white px-4 py-2 font-bold text-[#08284d]">🛒 {ar?"السلة":"Cart"}</Link><Link to="/purchases" className="rounded-xl border bg-white px-4 py-2 font-bold text-[#08284d]">🧾 {ar?"المشتريات والفواتير":"Purchases & Invoices"}</Link><Link to="/refunds" className="rounded-xl border bg-white px-4 py-2 font-bold text-[#08284d]">↩ {ar?"الاسترداد":"Refunds"}</Link></div>
 <section className="mt-8"><div className="flex items-end justify-between gap-3"><div><h2 className="academy-title text-2xl">{ar?"واصل التعلم":"Continue Learning"}</h2><p className="mt-1 text-sm text-slate-500">{ar?"ارجع مباشرة إلى دوراتك الحالية.":"Jump back into your active courses."}</p></div><Link to="/my-courses" className="font-bold text-[#f97316]">{ar?"كل الدورات":"All courses"}</Link></div>
 <div className="mt-5 grid gap-5 md:grid-cols-2">{continueItems.map(e=>{const c=e.courses;if(!c)return null;const progress=Number(e.progress||0);return <article key={e.id} className="academy-card overflow-hidden sm:flex"><img src={c.image||"https://placehold.co/800x450?text=Course"} className="aspect-video w-full object-cover sm:w-48" alt={c.title}/><div className="flex-1 p-5"><h3 className="font-extrabold text-[#08284d]">{c.title}</h3><div className="mt-4 flex justify-between text-xs text-slate-500"><span>{ar?"التقدم":"Progress"}</span><b dir="ltr">{progress}%</b></div><div className="academy-progress mt-2"><span style={{width:`${progress}%`}}/></div><Link to={`/learn/${c.id}`} className="academy-btn-dark mt-4 text-sm">{ar?"متابعة التعلم":"Resume Learning"}</Link></div></article>})}{!continueItems.length&&<div className="academy-card p-8 text-center text-slate-500 md:col-span-2">{ar?"لا توجد دورة قيد التقدم الآن.":"No course in progress right now."}</div>}</div></section></>}
 </div></main></MainLayout>
}
function Metric({icon,label,value,to}){return <Link to={to} className="academy-card p-4 hover:-translate-y-0.5 hover:shadow-lg"><div className="text-xl text-[#f97316]">{icon}</div><div className="mt-2 text-xs font-semibold text-slate-500">{label}</div><div className="mt-1 text-2xl font-extrabold text-[#08284d]">{value}</div></Link>}
