import {useEffect,useState} from "react";
import {FaEdit,FaPlus,FaSave,FaTimes} from "react-icons/fa";
import {getSchoolCore,saveAcademicYear} from "../../../services/schoolService";
const fresh=()=>({id:null,name:"",starts_on:"",ends_on:"",is_current:false,status:"draft"});
export default function AcademicYears(){
 const[data,setData]=useState(null),[form,setForm]=useState(fresh()),[saving,setSaving]=useState(false);
 async function load(){setData(await getSchoolCore())}
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 function edit(y){setForm({id:y.id,name:y.name,starts_on:y.starts_on,ends_on:y.ends_on,is_current:y.is_current,status:y.status});window.scrollTo({top:0,behavior:"smooth"})}
 async function submit(e){e.preventDefault();try{setSaving(true);await saveAcademicYear(form);const was=!!form.id;setForm(fresh());await load();alert(was?"تم تحديث العام الدراسي":"تم إضافة العام الدراسي")}catch(e){alert(e.message)}finally{setSaving(false)}}
 return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold text-[#12345b]">السنوات الدراسية</h1><p className="mt-2 text-slate-500">إضافة وتعديل العام الدراسي وحالته.</p></div>{form.id&&<button onClick={()=>setForm(fresh())} className="academy-btn-dark"><FaTimes/>إلغاء التعديل</button>}</div><div className="mt-6 grid gap-6 lg:grid-cols-[420px_1fr]"><form onSubmit={submit} className="academy-card space-y-4 p-5"><h2 className="font-extrabold text-[#12345b]">{form.id?"تعديل العام الدراسي":"عام دراسي جديد"}</h2><Field label="اسم العام"><input required className="academy-input" placeholder="2026/2027" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="بداية العام"><input required type="date" className="academy-input" value={form.starts_on} onChange={e=>setForm({...form,starts_on:e.target.value})}/></Field><Field label="نهاية العام"><input required type="date" className="academy-input" value={form.ends_on} onChange={e=>setForm({...form,ends_on:e.target.value})}/></Field></div><Field label="الحالة"><select className="academy-input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">مسودة</option><option value="active">نشط</option><option value="closed">مغلق</option></select></Field><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={form.is_current} onChange={e=>setForm({...form,is_current:e.target.checked})}/>العام الدراسي الحالي</label><button disabled={saving} className="academy-btn-primary w-full">{form.id?<FaSave/>:<FaPlus/>}{saving?"جاري الحفظ...":form.id?"حفظ التعديلات":"إضافة العام"}</button></form><div className="space-y-3">{(data?.years||[]).map(y=><div key={y.id} className="academy-card flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="text-xl font-extrabold text-[#12345b]">{y.name}</div><div dir="ltr" className="mt-1 text-sm text-slate-500">{y.starts_on} → {y.ends_on}</div></div><div className="flex items-center gap-2"><button onClick={()=>edit(y)} className="rounded-lg bg-orange-50 p-2 text-orange-600"><FaEdit/></button><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{y.status}</span>{y.is_current&&<span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">الحالي</span>}</div></div>)}</div></div></div>
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-sm font-bold">{label}</span>{children}</label>}
