import {useEffect,useState} from "react";
import {FaBriefcase,FaCalendarCheck,FaFileContract,FaMoneyCheckAlt,FaStar,FaUsers} from "react-icons/fa";
import {getSchoolEmployees,getSchoolEmployeeHRProfile,getSchoolHRDashboard,saveSchoolPerformanceReview} from "../../../services/schoolService";

export default function HRControlCenter(){
 const[dash,setDash]=useState({}),[employees,setEmployees]=useState([]),[employeeId,setEmployeeId]=useState(""),[profile,setProfile]=useState(null),[tab,setTab]=useState("dashboard");
 const[review,setReview]=useState({review_period_start:new Date(new Date().getFullYear(),0,1).toISOString().slice(0,10),review_period_end:new Date().toISOString().slice(0,10),attendance_score:80,performance_score:80,behavior_score:80,strengths:"",improvement_areas:"",manager_comment:"",final:false});
 async function load(){const[d,e]=await Promise.all([getSchoolHRDashboard(),getSchoolEmployees()]);setDash(d);setEmployees(e);const id=employeeId||e[0]?.id||"";setEmployeeId(id);if(id)setProfile(await getSchoolEmployeeHRProfile(id))}
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 async function choose(id){setEmployeeId(id);setProfile(await getSchoolEmployeeHRProfile(id));setTab("employee")}
 async function saveReview(e){e.preventDefault();await saveSchoolPerformanceReview({...review,employee_id:employeeId});setProfile(await getSchoolEmployeeHRProfile(employeeId));alert("تم حفظ التقييم")}
 return <div><h1 className="text-3xl font-extrabold text-[#12345b]">مركز الموارد البشرية</h1><p className="mt-2 text-slate-500">الموظفون، العقود، الحضور، الإجازات، الرواتب وتقييم الأداء.</p>
 <div className="mt-5 flex gap-2">{[["dashboard","الملخص"],["employee","ملف الموظف"],["review","تقييم الأداء"]].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-xl px-4 py-2 font-bold ${tab===k?"bg-[#12345b] text-white":"bg-white border"}`}>{l}</button>)}</div>
 {tab==="dashboard"&&<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[
 ["الموظفون النشطون",dash.employees_active,FaUsers],["العقود النشطة",dash.active_contracts,FaFileContract],["إجازات معلقة",dash.pending_leave_requests,FaCalendarCheck],["الحضور اليوم",dash.attendance_today,FaBriefcase],["متأخرون اليوم",dash.late_today,FaCalendarCheck],["عقود تنتهي خلال 30 يوم",dash.contracts_expiring_30_days,FaFileContract],["تقييمات الأداء",dash.performance_reviews,FaStar],["مسيرات الرواتب",dash.payroll_runs,FaMoneyCheckAlt]
 ].map(([t,v,I])=><div key={t} className="academy-card p-5"><div className="flex justify-between"><div><div className="text-sm text-slate-500">{t}</div><div className="mt-2 text-3xl font-extrabold text-[#12345b]">{v||0}</div></div><I className="text-2xl text-orange-500"/></div></div>)}</div>}
 {tab==="employee"&&<div className="mt-5 grid gap-6 xl:grid-cols-[360px_1fr]"><div className="academy-card p-5"><select className="academy-input" value={employeeId} onChange={e=>choose(e.target.value)}>{employees.map(x=><option key={x.id} value={x.id}>{x.employee_no} — {x.full_name_ar}</option>)}</select></div><div className="space-y-4">{profile&&<><div className="academy-card p-5"><h2 className="text-xl font-extrabold text-[#12345b]">{profile.employee?.full_name_ar}</h2><div className="mt-2 text-sm text-slate-500">{profile.employee?.job_title_ar} • {profile.employee?.employment_type} • {profile.employee?.status}</div></div><div className="grid gap-3 md:grid-cols-4">{Object.entries(profile.attendance_summary||{}).map(([k,v])=><div key={k} className="academy-card p-4"><div className="text-xs text-slate-500">{k}</div><b>{v}</b></div>)}</div><div className="academy-card p-5"><h3 className="font-extrabold">العقود</h3>{(profile.contracts||[]).map(c=><div key={c.id} className="border-b py-3 text-sm">{c.contract_no} • {c.starts_on} → {c.ends_on||"مفتوح"} • {c.status}</div>)}</div><div className="academy-card p-5"><h3 className="font-extrabold">الإجازات</h3>{(profile.leaves||[]).map(l=><div key={l.id} className="border-b py-3 text-sm">{l.leave_type} • {l.starts_on} → {l.ends_on} • {l.status}</div>)}</div></>}</div></div>}
 {tab==="review"&&<form onSubmit={saveReview} className="academy-card mt-5 max-w-2xl space-y-4 p-5"><select className="academy-input" value={employeeId} onChange={e=>setEmployeeId(e.target.value)}>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name_ar}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><input type="date" className="academy-input" value={review.review_period_start} onChange={e=>setReview({...review,review_period_start:e.target.value})}/><input type="date" className="academy-input" value={review.review_period_end} onChange={e=>setReview({...review,review_period_end:e.target.value})}/></div><div className="grid gap-3 sm:grid-cols-3"><Score l="الحضور" v={review.attendance_score} set={v=>setReview({...review,attendance_score:v})}/><Score l="الأداء" v={review.performance_score} set={v=>setReview({...review,performance_score:v})}/><Score l="السلوك" v={review.behavior_score} set={v=>setReview({...review,behavior_score:v})}/></div><textarea className="academy-input min-h-20" placeholder="نقاط القوة" value={review.strengths} onChange={e=>setReview({...review,strengths:e.target.value})}/><textarea className="academy-input min-h-20" placeholder="نقاط التحسين" value={review.improvement_areas} onChange={e=>setReview({...review,improvement_areas:e.target.value})}/><textarea className="academy-input min-h-20" placeholder="تعليق المدير" value={review.manager_comment} onChange={e=>setReview({...review,manager_comment:e.target.value})}/><label className="flex gap-2 font-bold"><input type="checkbox" checked={review.final} onChange={e=>setReview({...review,final:e.target.checked})}/>اعتماد التقييم نهائيًا</label><button className="academy-btn-primary w-full">حفظ التقييم</button></form>}
 </div>
}
function Score({l,v,set}){return <label><span className="mb-1 block text-sm font-bold">{l}</span><input type="number" min="0" max="100" className="academy-input" value={v} onChange={e=>set(e.target.value)}/></label>}
