import {useEffect,useState} from "react";
import {FaEdit,FaPlus,FaSave,FaTimes} from "react-icons/fa";
import {getSchoolCore,getSchoolGradeSubjects,getSchoolSubjects,saveSchoolGradeSubject,saveSchoolSubject} from "../../../services/schoolService";
const fresh=()=>({id:null,code:"",name_ar:"",name_en:"",description_ar:"",description_en:"",is_active:true});
const allocFresh=()=>({id:null,academic_year_id:"",grade_level_id:"",curriculum_id:"",subject_id:"",weekly_periods:"4",pass_mark:"50",max_mark:"100",sort_order:"1",is_active:true});
export default function Subjects(){
 const[data,setData]=useState(null),[subjects,setSubjects]=useState([]),[allocations,setAllocations]=useState([]),[form,setForm]=useState(fresh()),[alloc,setAlloc]=useState(allocFresh()),[saving,setSaving]=useState(false),[mode,setMode]=useState("subject");
 async function load(){const[c,s,a]=await Promise.all([getSchoolCore(),getSchoolSubjects(),getSchoolGradeSubjects()]);setData(c);setSubjects(s);setAllocations(a);setAlloc(v=>({...v,academic_year_id:v.academic_year_id||c.years.find(x=>x.is_current)?.id||"",grade_level_id:v.grade_level_id||c.grades[0]?.id||"",curriculum_id:v.curriculum_id||c.curricula[0]?.id||"",subject_id:v.subject_id||s[0]?.id||""}))}
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 function editSubject(x){setMode("subject");setForm({...x});window.scrollTo({top:0,behavior:"smooth"})}
 async function submit(e){e.preventDefault();try{setSaving(true);const editing=!!form.id;await saveSchoolSubject(form);setForm(fresh());await load();alert(editing?"تم تحديث المادة":"تم إضافة المادة")}catch(e){alert(e.message)}finally{setSaving(false)}}
 function editAllocation(x){setMode("allocation");setAlloc({id:x.id,academic_year_id:x.academic_year_id,grade_level_id:x.grade_level_id,curriculum_id:x.curriculum_id,subject_id:x.subject_id,weekly_periods:String(x.weekly_periods||1),pass_mark:String(x.pass_mark||50),max_mark:String(x.max_mark||100),sort_order:String(x.sort_order||1),is_active:x.is_active!==false});window.scrollTo({top:0,behavior:"smooth"})}
 function resetAllocation(){setAlloc({id:null,academic_year_id:data?.years.find(x=>x.is_current)?.id||"",grade_level_id:data?.grades[0]?.id||"",curriculum_id:data?.curricula[0]?.id||"",subject_id:subjects[0]?.id||"",weekly_periods:"4",pass_mark:"50",max_mark:"100",sort_order:"1",is_active:true})}
 async function saveAlloc(e){e.preventDefault();try{setSaving(true);await saveSchoolGradeSubject(alloc);const editing=!!alloc.id;resetAllocation();await load();alert(editing?"تم تحديث توزيع المادة":"تم حفظ توزيع المادة")}catch(e){alert(e.message)}finally{setSaving(false)}}
 return <div><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold text-[#12345b]">المواد الدراسية</h1><p className="mt-2 text-slate-500">إضافة وتعديل وتعطيل المواد، مع توزيعها على الصفوف والمناهج.</p></div><div className="flex gap-2"><button onClick={()=>{setMode("subject");setForm(fresh())}} className={`rounded-xl px-4 py-2 font-bold ${mode==="subject"?"bg-orange-500 text-white":"bg-white"}`}>المواد</button><button onClick={()=>setMode("allocation")} className={`rounded-xl px-4 py-2 font-bold ${mode==="allocation"?"bg-orange-500 text-white":"bg-white"}`}>توزيع المواد</button></div></div>
 <div className="grid gap-6 lg:grid-cols-[430px_1fr]">
 {mode==="subject"?<form onSubmit={submit} className="academy-card space-y-4 p-5"><div className="flex justify-between"><h2 className="font-extrabold text-[#12345b]">{form.id?"تعديل المادة":"مادة جديدة"}</h2>{form.id&&<button type="button" onClick={()=>setForm(fresh())}><FaTimes/></button>}</div><Field label="رمز المادة"><input required className="academy-input" placeholder="MATH" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></Field><Field label="اسم المادة بالعربية"><input required className="academy-input" value={form.name_ar} onChange={e=>setForm({...form,name_ar:e.target.value})}/></Field><Field label="اسم المادة بالإنجليزية"><input required className="academy-input" value={form.name_en} onChange={e=>setForm({...form,name_en:e.target.value})}/></Field><Field label="الوصف بالعربية"><textarea className="academy-input min-h-20" value={form.description_ar||""} onChange={e=>setForm({...form,description_ar:e.target.value})}/></Field><Field label="الوصف بالإنجليزية"><textarea className="academy-input min-h-20" value={form.description_en||""} onChange={e=>setForm({...form,description_en:e.target.value})}/></Field><label className="flex gap-2 font-bold"><input type="checkbox" checked={form.is_active!==false} onChange={e=>setForm({...form,is_active:e.target.checked})}/>المادة نشطة</label><button disabled={saving} className="academy-btn-primary w-full">{form.id?<FaSave/>:<FaPlus/>}{form.id?"حفظ التعديلات":"إضافة المادة"}</button></form>:
 <form onSubmit={saveAlloc} className="academy-card space-y-4 p-5"><div className="flex justify-between"><h2 className="font-extrabold text-[#12345b]">{alloc.id?"تعديل توزيع المادة":"توزيع مادة على المستوى"}</h2>{alloc.id&&<button type="button" onClick={resetAllocation}><FaTimes/></button>}</div><Field label="العام"><select required disabled={!!alloc.id} className="academy-input" value={alloc.academic_year_id} onChange={e=>setAlloc({...alloc,academic_year_id:e.target.value})}>{(data?.years||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="المستوى"><select required disabled={!!alloc.id} className="academy-input" value={alloc.grade_level_id} onChange={e=>setAlloc({...alloc,grade_level_id:e.target.value})}>{(data?.grades||[]).map(x=><option key={x.id} value={x.id}>{x.name_ar} / {x.name_en}</option>)}</select></Field><Field label="المنهج"><select required disabled={!!alloc.id} className="academy-input" value={alloc.curriculum_id} onChange={e=>setAlloc({...alloc,curriculum_id:e.target.value})}>{(data?.curricula||[]).map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></Field><Field label="المادة"><select required disabled={!!alloc.id} className="academy-input" value={alloc.subject_id} onChange={e=>setAlloc({...alloc,subject_id:e.target.value})}>{subjects.map(x=><option key={x.id} value={x.id}>{x.name_ar} / {x.name_en}</option>)}</select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="حصص أسبوعية"><input type="number" min="1" className="academy-input" value={alloc.weekly_periods} onChange={e=>setAlloc({...alloc,weekly_periods:e.target.value})}/></Field><Field label="درجة النجاح %"><input type="number" min="0" max="100" className="academy-input" value={alloc.pass_mark} onChange={e=>setAlloc({...alloc,pass_mark:e.target.value})}/></Field></div><Field label="الدرجة القصوى"><input type="number" min="1" className="academy-input" value={alloc.max_mark} onChange={e=>setAlloc({...alloc,max_mark:e.target.value})}/></Field><label className="flex gap-2 font-bold"><input type="checkbox" checked={alloc.is_active!==false} onChange={e=>setAlloc({...alloc,is_active:e.target.checked})}/>التوزيع نشط</label><button disabled={saving} className="academy-btn-dark w-full">{alloc.id?"حفظ التعديلات":"حفظ التوزيع"}</button></form>}
 <div>{mode==="subject"?<div className="grid gap-3 md:grid-cols-2">{subjects.map(x=><div key={x.id} className={`academy-card p-5 ${x.is_active===false?"opacity-60":""}`}><div className="flex justify-between gap-3"><div><div dir="ltr" className="text-xs font-bold text-orange-600">{x.code}</div><h2 className="mt-1 font-extrabold text-[#12345b]">{x.name_ar}</h2><div className="text-sm text-slate-500">{x.name_en}</div></div><button onClick={()=>editSubject(x)} className="text-orange-600"><FaEdit/></button></div></div>)}</div>:<div className="space-y-3">{allocations.map(x=><div key={x.id} className="academy-card flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="text-xs font-bold text-orange-600">{x.school_academic_years?.name} • {x.school_curricula?.name_ar}</div><h3 className="mt-1 font-extrabold text-[#12345b]">{x.school_subjects?.name_ar} — {x.school_grade_levels?.name_ar}</h3></div><div className="flex items-center gap-3"><div className="text-end text-sm"><b>{x.weekly_periods} حصص/أسبوع</b><div className="mt-1 text-xs text-slate-500">النجاح {x.pass_mark}%</div></div><button onClick={()=>editAllocation(x)} className="rounded-lg bg-orange-50 p-2 text-orange-600"><FaEdit/></button></div></div>)}</div>}</div>
 </div></div>
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-sm font-bold text-slate-700">{label}</span>{children}</label>}
