import {useEffect,useState} from "react";
import {FaEdit,FaPlus,FaSave,FaTimes} from "react-icons/fa";
import {getSchoolCore,saveClassSection} from "../../../services/schoolService";
const fresh=()=>({id:null,academic_year_id:"",grade_level_id:"",curriculum_id:"",section_name:"A",capacity:"",is_active:true});
export default function Classes(){
 const[data,setData]=useState(null),[form,setForm]=useState(fresh()),[saving,setSaving]=useState(false);
 async function load(){const d=await getSchoolCore();setData(d);setForm(f=>({...f,academic_year_id:f.academic_year_id||d.years.find(x=>x.is_current)?.id||"",curriculum_id:f.curriculum_id||d.curricula[0]?.id||"",grade_level_id:f.grade_level_id||d.grades[0]?.id||""}))}
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 function edit(x){setForm({id:x.id,academic_year_id:x.academic_year_id,grade_level_id:x.grade_level_id,curriculum_id:x.curriculum_id,section_name:x.section_name,capacity:x.capacity??"",is_active:x.is_active!==false});window.scrollTo({top:0,behavior:"smooth"})}
 function reset(){const d=data;setForm({id:null,academic_year_id:d?.years.find(x=>x.is_current)?.id||"",grade_level_id:d?.grades[0]?.id||"",curriculum_id:d?.curricula[0]?.id||"",section_name:"A",capacity:"",is_active:true})}
 async function submit(e){e.preventDefault();try{setSaving(true);const editing=!!form.id;await saveClassSection(form);reset();await load();alert(editing?"تم تحديث الفصل":"تم إنشاء الفصل")}catch(e){alert(e.message)}finally{setSaving(false)}}
 return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold text-[#12345b]">الفصول الدراسية</h1><p className="mt-2 text-slate-500">إنشاء وتعديل وتعطيل الفصول حسب العام والصف والمنهج.</p></div>{form.id&&<button onClick={reset} className="academy-btn-dark"><FaTimes/>إلغاء التعديل</button>}</div>
 <div className="mt-6 grid gap-6 lg:grid-cols-[440px_1fr]"><form onSubmit={submit} className="academy-card space-y-4 p-5"><h2 className="font-extrabold text-[#12345b]">{form.id?"تعديل الفصل":"فصل جديد"}</h2><Field label="العام الدراسي"><select required className="academy-input" value={form.academic_year_id} onChange={e=>setForm({...form,academic_year_id:e.target.value})}><option value="">اختر</option>{(data?.years||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="المستوى"><select required className="academy-input" value={form.grade_level_id} onChange={e=>setForm({...form,grade_level_id:e.target.value})}>{(data?.grades||[]).map(x=><option key={x.id} value={x.id}>{x.name_ar} / {x.name_en}</option>)}</select></Field><Field label="المنهج"><select required className="academy-input" value={form.curriculum_id} onChange={e=>setForm({...form,curriculum_id:e.target.value})}>{(data?.curricula||[]).map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="اسم الفصل"><input required className="academy-input" value={form.section_name} onChange={e=>setForm({...form,section_name:e.target.value})}/></Field><Field label="السعة"><input type="number" min="1" className="academy-input" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></Field></div><label className="flex gap-2 font-bold"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>الفصل نشط</label><button disabled={saving||!data?.years?.length} className="academy-btn-primary w-full">{form.id?<FaSave/>:<FaPlus/>}{saving?"جاري الحفظ...":form.id?"حفظ التعديلات":"إنشاء الفصل"}</button></form>
 <div className="space-y-3">{(data?.sections||[]).map(x=><div key={x.id} className={`academy-card flex flex-wrap items-center justify-between gap-3 p-5 ${x.is_active===false?"opacity-60":""}`}><div><div className="font-extrabold text-[#12345b]">{x.school_grade_levels?.name_ar} — فصل {x.section_name}</div><div className="mt-1 text-sm text-slate-500">{x.school_curricula?.name_ar}</div></div><div className="flex items-center gap-3"><div className="text-sm font-bold text-orange-600">{x.capacity?`السعة ${x.capacity}`:"بدون حد"}</div><button onClick={()=>edit(x)} className="rounded-lg bg-orange-50 p-2 text-orange-600"><FaEdit/></button></div></div>)}</div></div></div>
}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-sm font-bold text-slate-700">{label}</span>{children}</label>}
