import {useEffect,useMemo,useState} from "react";
import {FaEdit,FaPlus,FaSave,FaTimes} from "react-icons/fa";
import {getSchoolCore,saveSchoolCurriculum,saveSchoolGradeLevel,saveSchoolStage} from "../../../services/schoolService";
const stageFresh=()=>({id:null,code:"",name_ar:"",name_en:"",sort_order:"1",is_active:true});
const gradeFresh=()=>({id:null,stage_id:"",code:"",name_ar:"",name_en:"",grade_number:"1",sort_order:"1",is_active:true});
const curriculumFresh=()=>({id:null,code:"",name_ar:"",name_en:"",instruction_language:"ar",is_active:true});
export default function Structure(){
 const[data,setData]=useState(null),[kind,setKind]=useState("stage"),[stage,setStage]=useState(stageFresh()),[grade,setGrade]=useState(gradeFresh()),[curriculum,setCurriculum]=useState(curriculumFresh());
 async function load(){const d=await getSchoolCore();setData(d);setGrade(g=>({...g,stage_id:g.stage_id||d.stages[0]?.id||""}))}
 useEffect(()=>{load().catch(e=>alert(e.message))},[]);
 const grouped=useMemo(()=>{const m={};for(const s of data?.stages||[])m[s.id]={...s,grades:[]};for(const g of data?.grades||[])if(m[g.stage_id])m[g.stage_id].grades.push(g);return Object.values(m).sort((a,b)=>a.sort_order-b.sort_order)},[data]);
 async function saveStage(e){e.preventDefault();try{await saveSchoolStage(stage);setStage(stageFresh());await load()}catch(e){alert(e.message)}}
 async function saveGrade(e){e.preventDefault();try{await saveSchoolGradeLevel(grade);setGrade({...gradeFresh(),stage_id:data?.stages?.[0]?.id||""});await load()}catch(e){alert(e.message)}}
 async function saveCurr(e){e.preventDefault();try{await saveSchoolCurriculum(curriculum);setCurriculum(curriculumFresh());await load()}catch(e){alert(e.message)}}
 return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold text-[#12345b]">المراحل والصفوف والمناهج</h1><p className="mt-2 text-slate-500">إضافة وتعديل وتعطيل البيانات الأساسية للهيكل الدراسي.</p></div><div className="flex gap-2">{[["stage","مرحلة"],["grade","صف/مستوى"],["curriculum","منهج"]].map(([k,l])=><button key={k} onClick={()=>setKind(k)} className={`rounded-xl px-4 py-2 font-bold ${kind===k?"bg-orange-500 text-white":"bg-white"}`}>{l}</button>)}</div></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-[430px_1fr]"><div>
 {kind==="stage"&&<form onSubmit={saveStage} className="academy-card space-y-4 p-5"><Header editing={stage.id} reset={()=>setStage(stageFresh())} title="المرحلة"/><Field l="الرمز"><input required className="academy-input" value={stage.code} onChange={e=>setStage({...stage,code:e.target.value})}/></Field><Field l="الاسم بالعربية"><input required className="academy-input" value={stage.name_ar} onChange={e=>setStage({...stage,name_ar:e.target.value})}/></Field><Field l="الاسم بالإنجليزية"><input required className="academy-input" value={stage.name_en} onChange={e=>setStage({...stage,name_en:e.target.value})}/></Field><Field l="الترتيب"><input required type="number" className="academy-input" value={stage.sort_order} onChange={e=>setStage({...stage,sort_order:e.target.value})}/></Field><Active v={stage.is_active} set={v=>setStage({...stage,is_active:v})}/><Save editing={stage.id}/></form>}
 {kind==="grade"&&<form onSubmit={saveGrade} className="academy-card space-y-4 p-5"><Header editing={grade.id} reset={()=>setGrade({...gradeFresh(),stage_id:data?.stages?.[0]?.id||""})} title="الصف/المستوى"/><Field l="المرحلة"><select className="academy-input" value={grade.stage_id} onChange={e=>setGrade({...grade,stage_id:e.target.value})}>{(data?.stages||[]).map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></Field><Field l="الرمز"><input required className="academy-input" value={grade.code} onChange={e=>setGrade({...grade,code:e.target.value})}/></Field><Field l="الاسم بالعربية"><input required className="academy-input" value={grade.name_ar} onChange={e=>setGrade({...grade,name_ar:e.target.value})}/></Field><Field l="الاسم بالإنجليزية"><input required className="academy-input" value={grade.name_en} onChange={e=>setGrade({...grade,name_en:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field l="رقم المستوى"><input type="number" className="academy-input" value={grade.grade_number} onChange={e=>setGrade({...grade,grade_number:e.target.value})}/></Field><Field l="الترتيب"><input type="number" className="academy-input" value={grade.sort_order} onChange={e=>setGrade({...grade,sort_order:e.target.value})}/></Field></div><Active v={grade.is_active} set={v=>setGrade({...grade,is_active:v})}/><Save editing={grade.id}/></form>}
 {kind==="curriculum"&&<form onSubmit={saveCurr} className="academy-card space-y-4 p-5"><Header editing={curriculum.id} reset={()=>setCurriculum(curriculumFresh())} title="المنهج"/><Field l="الرمز"><input required className="academy-input" value={curriculum.code} onChange={e=>setCurriculum({...curriculum,code:e.target.value})}/></Field><Field l="الاسم بالعربية"><input required className="academy-input" value={curriculum.name_ar} onChange={e=>setCurriculum({...curriculum,name_ar:e.target.value})}/></Field><Field l="الاسم بالإنجليزية"><input required className="academy-input" value={curriculum.name_en} onChange={e=>setCurriculum({...curriculum,name_en:e.target.value})}/></Field><Field l="لغة التدريس"><select className="academy-input" value={curriculum.instruction_language} onChange={e=>setCurriculum({...curriculum,instruction_language:e.target.value})}><option value="ar">العربية</option><option value="en">English</option></select></Field><Active v={curriculum.is_active} set={v=>setCurriculum({...curriculum,is_active:v})}/><Save editing={curriculum.id}/></form>}
 </div>
 <div><div className="grid gap-5 lg:grid-cols-2">{grouped.map(st=><section key={st.id} className="academy-card overflow-hidden"><div className="flex items-center justify-between bg-[#12345b] px-5 py-4 text-white"><div><h2 className="text-xl font-extrabold">{st.name_ar}</h2><div className="text-xs text-slate-300">{st.name_en}</div></div><button onClick={()=>{setKind("stage");setStage({...st})}} className="rounded-lg bg-white/10 p-2"><FaEdit/></button></div><div className="grid gap-3 p-5 sm:grid-cols-2">{st.grades.map(g=><div key={g.id} className="rounded-xl border bg-slate-50 p-4"><div className="flex justify-between gap-2"><div><div className="font-extrabold text-[#12345b]">{g.name_ar}</div><div className="text-xs text-slate-500">{g.name_en}</div></div><button onClick={()=>{setKind("grade");setGrade({...g})}} className="text-orange-600"><FaEdit/></button></div></div>)}</div></section>)}</div><div className="mt-5 academy-card p-5"><h2 className="font-extrabold text-[#12345b]">المناهج</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{(data?.curricula||[]).map(c=><div key={c.id} className="flex items-center justify-between rounded-xl border p-4"><div><b>{c.name_ar}</b><div className="text-sm text-slate-500">{c.name_en}</div></div><button onClick={()=>{setKind("curriculum");setCurriculum({...c})}} className="text-orange-600"><FaEdit/></button></div>)}</div></div></div></div></div>
}
function Header({editing,reset,title}){return <div className="flex items-center justify-between"><h2 className="font-extrabold text-[#12345b]">{editing?`تعديل ${title}`:`إضافة ${title}`}</h2>{editing&&<button type="button" onClick={reset} className="text-slate-500"><FaTimes/></button>}</div>}
function Field({l,children}){return <label className="block"><span className="mb-1.5 block text-sm font-bold">{l}</span>{children}</label>}
function Active({v,set}){return <label className="flex gap-2 font-bold"><input type="checkbox" checked={v} onChange={e=>set(e.target.checked)}/>نشط</label>}
function Save({editing}){return <button className="academy-btn-primary w-full">{editing?<FaSave/>:<FaPlus/>}{editing?"حفظ التعديلات":"إضافة"}</button>}
