import {useEffect,useState} from "react";
import {FaBookmark,FaStickyNote,FaTrash} from "react-icons/fa";
import {addLessonBookmark,addLessonNote,deleteLessonBookmark,deleteLessonNote,getLessonBookmarks,getLessonNotes} from "../services/proAcademyFinalService";
export default function LearningTools({courseId,lessonId,currentSeconds=null}){
 const[notes,setNotes]=useState([]),[bookmarks,setBookmarks]=useState([]),[text,setText]=useState("");
 async function load(){if(!lessonId)return;const[n,b]=await Promise.all([getLessonNotes(lessonId),getLessonBookmarks(lessonId)]);setNotes(n);setBookmarks(b)}
 useEffect(()=>{load()},[lessonId]);
 async function addNote(e){e.preventDefault();if(!text.trim())return;await addLessonNote({courseId,lessonId,noteText:text,timestampSeconds:currentSeconds});setText("");await load()}
 async function bookmark(){await addLessonBookmark({courseId,lessonId,timestampSeconds:currentSeconds});await load()}
 return <div className="mt-6 grid gap-4 border-t pt-5 lg:grid-cols-2"><section className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><h3 className="font-extrabold text-[#08284d]"><FaStickyNote className="me-2 inline"/>ملاحظاتي</h3><span className="text-xs text-slate-400">{notes.length}</span></div><form onSubmit={addNote} className="mt-3"><textarea value={text} onChange={e=>setText(e.target.value)} className="academy-input min-h-20" placeholder="اكتب ملاحظة عن هذا الدرس..."/><button className="academy-btn-dark mt-2 text-sm">حفظ الملاحظة</button></form><div className="mt-3 space-y-2">{notes.slice(0,6).map(n=><div key={n.id} className="rounded-xl bg-white p-3 text-sm"><div className="flex justify-between gap-2"><p className="leading-6">{n.note_text}</p><button onClick={async()=>{await deleteLessonNote(n.id);await load()}} className="text-red-500"><FaTrash/></button></div>{n.timestamp_seconds!=null&&<div className="mt-1 text-xs text-orange-600">@ {fmt(n.timestamp_seconds)}</div>}</div>)}</div></section><section className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><h3 className="font-extrabold text-[#08284d]"><FaBookmark className="me-2 inline"/>العلامات المرجعية</h3><button onClick={bookmark} className="rounded-xl bg-orange-50 px-3 py-2 text-sm font-bold text-orange-600">إضافة Bookmark</button></div><div className="mt-3 space-y-2">{bookmarks.map(b=><div key={b.id} className="flex items-center justify-between rounded-xl bg-white p-3 text-sm"><span>{b.timestamp_seconds!=null?`@ ${fmt(b.timestamp_seconds)}`:"هذا الدرس"}</span><button onClick={async()=>{await deleteLessonBookmark(b.id);await load()}} className="text-red-500"><FaTrash/></button></div>)}</div></section></div>
}
function fmt(v){const m=Math.floor(v/60),s=Math.floor(v%60);return `${m}:${String(s).padStart(2,"0")}`}
