import {useEffect,useState} from "react";
import {Navigate,useParams} from "react-router-dom";
import {useTranslation} from "react-i18next";
import MainLayout from "../layouts/MainLayout";
import {getCurrentUser,getEnrollment} from "../services/enrollmentService";
import {supabase} from "../services/supabase";
import {addCourseAnswer,addCourseQuestion,closeCourseQuestion,getCourseQuestions} from "../services/proAcademyFinalService";
export default function CourseQA(){
 const{courseId}=useParams();const{i18n}=useTranslation();const ar=i18n.language?.startsWith("ar");const[items,setItems]=useState([]),[course,setCourse]=useState(null),[loading,setLoading]=useState(true),[login,setLogin]=useState(false),[title,setTitle]=useState(""),[body,setBody]=useState(""),[reply,setReply]=useState({});
 async function load(){try{const u=await getCurrentUser();if(!u){setLogin(true);return}const [{data:c,error:ce},qs,en]=await Promise.all([supabase.from("courses").select("id,title").eq("id",courseId).single(),getCourseQuestions(courseId),getEnrollment(courseId,u.id)]);if(ce)throw ce;setCourse(c);setItems(qs);if(!en){const{data:i,error:ie}=await supabase.rpc("is_course_instructor",{p_course_id:courseId});if(ie)throw ie;if(!i)throw new Error(ar?"غير مصرح بالدخول":"Access denied")}}finally{setLoading(false)}}useEffect(()=>{load()},[courseId]);
 async function ask(e){e.preventDefault();await addCourseQuestion(courseId,title,body);setTitle("");setBody("");await load()}
 async function answer(q){const x=(reply[q.id]||"").trim();if(!x)return;await addCourseAnswer(q.id,x);setReply(v=>({...v,[q.id]:""}));await load()}
 if(login)return <Navigate to="/login" replace/>;
 return <MainLayout><main className="min-h-screen bg-[#f7f9fc] py-10"><div className="academy-container max-w-5xl"><h1 className="academy-title text-3xl">{ar?"الأسئلة والأجوبة":"Course Q&A"}</h1><p className="mt-2 text-slate-500">{course?.title}</p>{loading?<div className="academy-card mt-6 p-10 text-center">Loading...</div>:<><form onSubmit={ask} className="academy-card mt-6 p-5"><h2 className="font-extrabold text-[#08284d]">{ar?"اسأل سؤالًا":"Ask a Question"}</h2><input required value={title} onChange={e=>setTitle(e.target.value)} className="academy-input mt-3" placeholder={ar?"عنوان السؤال":"Question title"}/><textarea required value={body} onChange={e=>setBody(e.target.value)} className="academy-input mt-3 min-h-24" placeholder={ar?"اشرح سؤالك":"Describe your question"}/><button className="academy-btn-primary mt-3">{ar?"إرسال":"Post"}</button></form><div className="mt-6 space-y-4">{items.map(q=><article key={q.id} className="academy-card p-5"><div className="flex justify-between gap-3"><div><h3 className="font-extrabold text-[#08284d]">{q.title}</h3><p className="mt-2 leading-7 text-slate-600">{q.body}</p><div className="mt-2 text-xs text-slate-400">{q.profile?.full_name||q.profile?.email}</div></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{q.status}</span></div><div className="mt-4 space-y-3 border-t pt-4">{q.course_answers.map(a=><div key={a.id} className={`rounded-xl p-4 ${a.is_instructor?"bg-orange-50":"bg-slate-50"}`}><div className="text-xs font-bold text-slate-500">{a.is_instructor?(ar?"المدرب/الإدارة":"Instructor/Admin"):(a.profile?.full_name||a.profile?.email)}</div><p className="mt-1 text-sm leading-7">{a.body}</p></div>)}</div>{q.status!=="closed"&&<div className="mt-4 flex gap-2"><input value={reply[q.id]||""} onChange={e=>setReply(v=>({...v,[q.id]:e.target.value}))} className="academy-input" placeholder={ar?"أضف إجابة":"Add answer"}/><button onClick={()=>answer(q)} className="academy-btn-dark">{ar?"رد":"Reply"}</button></div>}</article>)}</div></>}</div></main></MainLayout>
}
