import {useEffect,useState} from "react";import {useTranslation} from "react-i18next";import {FaPen,FaTrash} from "react-icons/fa";import {supabase} from "../../services/supabase";import {AdminPageHeader,AdminCard,StatusBadge} from "../../components/admin/AdminUI";import {adminDeleteLearningPath,adminGetLearningPaths,adminSaveLearningPath} from "../../services/professionalAcademyService";
const empty={title:"",description:"",image_url:"",level:"",is_published:true};
export default function AdminLearningPaths(){const{i18n}=useTranslation();const ar=i18n.language?.startsWith("ar");const[items,setItems]=useState([]),[courses,setCourses]=useState([]),[form,setForm]=useState(empty),[selected,setSelected]=useState([]),[editing,setEditing]=useState(null),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const [p,c]=await Promise.all([adminGetLearningPaths(),supabase.from("courses").select("id,title,image,price").order("title")]);if(c.error)throw c.error;setItems(p);setCourses(c.data||[])}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 function reset(){setEditing(null);setForm(empty);setSelected([])}function edit(x){setEditing(x.id);setForm({title:x.title||"",description:x.description||"",image_url:x.image_url||"",level:x.level||"",is_published:x.is_published!==false});setSelected((x.learning_path_courses||[]).sort((a,b)=>a.order_number-b.order_number).map(v=>v.course_id))}
 function toggleCourse(id){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function save(e){e.preventDefault();try{await adminSaveLearningPath({...form,id:editing},selected);reset();await load()}catch(e){alert(e.message)}}async function remove(id){if(!confirm(ar?"حذف المسار؟":"Delete learning path?"))return;await adminDeleteLearningPath(id);await load()}
 return <div><AdminPageHeader title={ar?"المسارات التعليمية":"Learning Paths"} description={ar?"تجميع عدة دورات في مسار مهني منظم.":"Group multiple courses into structured career paths."}/>
  <div className="grid gap-6 xl:grid-cols-[440px_1fr]"><AdminCard className="p-5"><form onSubmit={save} className="space-y-4"><h2 className="font-extrabold text-[#08284d]">{editing?(ar?"تعديل المسار":"Edit Path"):(ar?"مسار جديد":"New Path")}</h2>
  <Field label={ar?"اسم المسار":"Path Title"}><input required className="academy-input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label={ar?"الوصف":"Description"}><textarea className="academy-input min-h-24" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label={ar?"صورة (رابط)":"Image URL"}><input dir="ltr" className="academy-input" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></Field><Field label={ar?"المستوى":"Level"}><input className="academy-input" value={form.level} onChange={e=>setForm({...form,level:e.target.value})}/></Field>
  <label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/>{ar?"منشور":"Published"}</label>
  <div><div className="mb-2 text-sm font-bold">{ar?"اختر الدورات بالترتيب":"Choose courses in order"}</div><div className="max-h-64 space-y-2 overflow-y-auto rounded-xl border p-2">{courses.map(c=><label key={c.id} className={`flex cursor-pointer items-center gap-3 rounded-lg p-2 ${selected.includes(c.id)?"bg-orange-50":"hover:bg-slate-50"}`}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>toggleCourse(c.id)}/><span className="text-sm font-semibold">{c.title}</span></label>)}</div></div>
  <div className="flex gap-2"><button className="academy-btn-primary flex-1">{ar?"حفظ":"Save"}</button>{editing&&<button type="button" onClick={reset} className="rounded-xl border px-4 font-bold">{ar?"إلغاء":"Cancel"}</button>}</div></form></AdminCard>
  <div className="grid gap-4 md:grid-cols-2">{loading?<AdminCard className="p-10 text-center md:col-span-2">{ar?"جاري التحميل...":"Loading..."}</AdminCard>:items.map(x=><AdminCard key={x.id} className="overflow-hidden"><img src={x.image_url||"https://placehold.co/800x450?text=Learning+Path"} className="aspect-video w-full object-cover"/><div className="p-5"><div className="flex justify-between gap-3"><h3 className="font-extrabold text-[#08284d]">{x.title}</h3><StatusBadge status={x.is_published?"published":"draft"}/></div><p className="mt-2 line-clamp-3 text-sm leading-7 text-slate-500">{x.description}</p><div className="mt-3 text-sm font-bold text-slate-600">{(x.learning_path_courses||[]).length} {ar?"دورة":"courses"}</div><div className="mt-4 flex justify-end gap-2 border-t pt-3"><button onClick={()=>edit(x)} className="flex h-9 w-9 items-center justify-center rounded-lg bg-orange-50 text-orange-600"><FaPen/></button><button onClick={()=>remove(x.id)} className="flex h-9 w-9 items-center justify-center rounded-lg bg-red-50 text-red-600"><FaTrash/></button></div></div></AdminCard>)}</div>
  </div></div>}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-sm font-bold">{label}</span>{children}</label>}
